### ISSUE TITLE
[브론즈1] 2309.일곱 난쟁이

### ISSUE THREAD

**Issue by skdudddl** [Hanbat-Algo-Study/algorithm#100]
🔗 문제 링크
https://www.acmicpc.net/problem/2309

💡 풀이 사항
📆풀이 일자: 2024.00.00
⏰풀이 시간: 00분 00초
✨채점 결과: 오답🙅‍♀️🙅‍♂️/시간 초과⌛/런타임 에러⏱/정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등

✍ 풀이 방법
(풀이 접근 및 방법에 대한 설명)

**Comment by skdudddl** [comment]
🔗 문제 링크
#94 

💡 풀이 사항
📆풀이 일자: 2024.01.24
⏰풀이 시간: 20분
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: 구현

✍ 풀이 방법

- 합 100이 되는 7명의 조합을 찾는 것은 반대로 전체에서 2명을 뺴서 100이 나오면 된다는 방식을 선택했다.
- 그래서 완전탐색을 이용해서 2명을 찾았고 그 두명을 0으로 바꿔줬다.
- 그리고 배열의 2번째부터 출력하는 방식으로 구현했다.

**Comment by GeonHui2** [comment]
### 🔗 문제 링크
#95 

### 💡 풀이 사항
📆풀이 일자: 2024.01.24
⏰풀이 시간: 15분
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: 구현

### ✍ 풀이 방법
- 전체 값을 더하고 전체 경우에서 2명씩 골라서 빼주고 100인 경우에 break를 시키고 해당 값들을 101로 바꿔줬다.
- 해당 배열을 정렬 후 출력했다.

**Comment by ramrami-S** [comment]
🔗 문제 링크
#123 

💡 풀이 사항
📆풀이 일자: 2024.01.26
⏰풀이 시간: 46분 53초
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: 구현(완탐..?)

✍ 풀이 방법
fake 난쟁이 번호를 0, 1로 초기화 하고 더해가면서 합이 100이되면 가짜 난쟁이 번호를 기억해 뒀다가 그 번호 난쟁이 빼고 출력한다

**Comment by ensk26** [comment]
### 🔗 문제 링크
https://github.com/Hanbat-Algo-Study/algorithm/pull/128

### 💡 풀이 사항
📆풀이 일자: 2024.01.14
⏰풀이 시간: 20분
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: 구현

### ✍ 풀이 방법
일곱난쟁이의 키가 합이 100이 되는 경우를 찾아야한다. 모든 경우의 수를 찾아 만족하는 경우를 구했다.
재귀 탐색으로 7명의 키 합이 100이 되는 경우 true로 넘겨주었다.
