### ISSUE TITLE
[실버4] 2567.색종이 - 2

### ISSUE THREAD

**Issue by skdudddl** [Hanbat-Algo-Study/algorithm#104]
🔗 문제 링크
https://www.acmicpc.net/problem/2567

💡 풀이 사항
📆풀이 일자: 2024.00.00
⏰풀이 시간: 00분 00초
✨채점 결과: 오답🙅‍♀️🙅‍♂️/시간 초과⌛/런타임 에러⏱/정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등

✍ 풀이 방법
(풀이 접근 및 방법에 대한 설명)

**Comment by GeonHui2** [comment]
### 🔗 문제 링크
#135  

### 💡 풀이 사항
📆풀이 일자: 2024.01.26
⏰풀이 시간: 1시간 30분
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: 구현

### ✍ 풀이 방법
- 색종이 1을 활용해서 문제를 해결했다.
- 둘레를 구하는 방법을 생각하는데 시간이 많이 소요되었다.
- 해당 부분이 채워진 부분이면 상, 하, 좌, 우를 확인하여서 채워지지 않은 부분이거나 범위를 벗어나면 result++을 해주었다.

**Comment by skdudddl** [comment]
🔗 문제 링크
https://github.com/Hanbat-Algo-Study/algorithm/pull/131

💡 풀이 사항
📆풀이 일자: 2024.01.26
⏰풀이 시간: 40분
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: 구현

✍ 풀이 방법

- 색종이 문제를 먼저 기초로 해뒀다.
- 처음 배열을 102x102로 설정해서  padding을 해줬다.
- 그래서 1부터 100까지 돌면서 false일때 cnt++해주는 방식으로 구현했다.

**Comment by jisooolee** [comment]
🔗 문제 링크
#154 

💡 풀이 사항
📆풀이 일자: 2024.01.29
⏰풀이 시간: 2시간 이상
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: 구현

✍ 풀이 방법

- 여기저기서 힌트를 얻었는데도 2시간 넘게 걸렸다ㅠ
- 101X101 int 배열에 색종이의 위치를 표시해주었다.
- 색종이의 둘레는 1로, 색종이의 면적에 해당하는 위치는 -1로, 그 외는 0으로 표시해주었다.
- 이후 배열을 탐색하면서, 값이 -1일 때 사방탐색을 진행하여 1을 찾으면 결과값을 1 증가해주었다.
