### ISSUE TITLE
[브론즈1] 2851.슈퍼 마리오

### ISSUE THREAD

**Issue by skdudddl** [Hanbat-Algo-Study/algorithm#107]
🔗 문제 링크
https://www.acmicpc.net/problem/2851

💡 풀이 사항
📆풀이 일자: 2024.00.00
⏰풀이 시간: 00분 00초
✨채점 결과: 오답🙅‍♀️🙅‍♂️/시간 초과⌛/런타임 에러⏱/정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등

✍ 풀이 방법
(풀이 접근 및 방법에 대한 설명)

**Comment by GeonHui2** [comment]
### 🔗 문제 링크
#136 

### 💡 풀이 사항
📆풀이 일자: 2024.01.27
⏰풀이 시간: 30분
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: 구현

### ✍ 풀이 방법
- 처음 구현 방식이 틀리고 다음 방식을 찾는데 시간이 오래 걸렸다.
- 누적값이 100이 넘지 않으면 누적값과 더한 값 중 더 가까운 값을 저장한다.

**Comment by skdudddl** [comment]
🔗 문제 링크
#153 

💡 풀이 사항
📆풀이 일자: 2024.01.27
⏰풀이 시간: 20분
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: 구현

✍ 풀이 방법
-  누적값이 100이 넘지 않으면 누적값과 더한 값 중 더 가까운 값을 저장한다.

**Comment by ramrami-S** [comment]
🔗 문제 링크
#166 

💡 풀이 사항
📆풀이 일자: 2024.01.30
⏰풀이 시간: 03분 03초
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: 구현

✍ 풀이 방법
점수를 더해가다가 100보다 크거나 같아지면 100점을 넘는 경우와 안넘는 경우 중 100점과 가까운 것을 정답으로 제출한다.
만약 두 경우 모두 100점과의 차이가 같으면 100점을 넘는 경우가 정답이다
총점이 100점이 안넘을 경우, 모든 점수의 합을 정답으로 제출한다.

**Comment by jisooolee** [comment]
🔗 문제 링크
#170

💡 풀이 사항
📆풀이 일자: 2024.01.30
⏰풀이 시간: 10분
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: 구현

✍ 풀이 방법
- mushrooms 배열에 버섯의 점수를 저장해준다.
- 배열을 순회하면서 버섯을 1개 먹었을 때의 점수 총합부터 전부 먹었을 때의 점수 총합까지 순차적으로 구한다.
- result에 100과의 차이가 가장 작은 총합을 저장한다.
- 만약 점수 총합이 100 이상이면서 100과의 차가 result와 100의 차보다 크다면 반복을 종료한다.

**Comment by ensk26** [comment]
https://github.com/Hanbat-Algo-Study/algorithm/pull/179

💡 풀이 사항
📆풀이 일자: 2024.01.29
⏰풀이 시간: 20분
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: 구현

✍ 풀이 방법
100과 근접한 값은 서로 값의 차 절대값으로 비교, 같은 경우 큰수를 저장, 중간에 끝기면 더이상 탐색을 안해 완탐으로 값을 더해가는 방식을 사용
