### ISSUE TITLE
[브론즈1] 2999.비밀 이메일

### ISSUE THREAD

**Issue by skdudddl** [Hanbat-Algo-Study/algorithm#109]
🔗 문제 링크
https://www.acmicpc.net/problem/2999

💡 풀이 사항
📆풀이 일자: 2024.00.00
⏰풀이 시간: 00분 00초
✨채점 결과: 오답🙅‍♀️🙅‍♂️/시간 초과⌛/런타임 에러⏱/정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등

✍ 풀이 방법
(풀이 접근 및 방법에 대한 설명)

**Comment by GeonHui2** [comment]
### 🔗 문제 링크
#137 

### 💡 풀이 사항
📆풀이 일자: 2024.01.27
⏰풀이 시간: 30분
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: 구현

### ✍ 풀이 방법
- 문자열을 행을 기준으로 나눠서 입력해 준다.
- 그 후 열을 기준으로 읽어주면서 문제를 구현했다.

**Comment by skdudddl** [comment]
🔗 문제 링크
#153

💡 풀이 사항
📆풀이 일자: 2024.01.27
⏰풀이 시간: 40분
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: 구현

✍ 풀이 방법

- 먼저 R,C를 구하고 C열이고 R행인 배열을 생성해준다.
- 그 배열에 알맞은 값을 넣어준다.
- 그리고 출력을 열다음 행으로 출력하는 방식으로 구현했다.

**Comment by ramrami-S** [comment]
🔗 문제 링크
#166

💡 풀이 사항
📆풀이 일자: 2024.01.30
⏰풀이 시간: 19분 33초
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: 구현

✍ 풀이 방법
~~살려죠,,~~

R, C를 먼저 알아내야 하는데 *N의 제곱근부터 시작해서 1씩 줄여나가면서 N과 나눌 때 나누어 떨어지는 수를 R로 설정하고, 
N에서 R을 나눈 수를 C로 둔다.
그 뒤로는 이차원 배열 탐색,,
* 6의 약수는1, 2, 3, 6, 36은 1, 2, 3, 4, 9, 12, 18, 36 이런 식으로 약수를 구할 때 대칭을 이루는 것을 볼 수 있다.
N의 제곱근을 a라고 할 때 a * a = N이므로 R이 C보다 작거나 같다는 문제의 조건이 있으므로 가장 큰 R은 N의 제곱근부터 찾으면 된다.

**Comment by jisooolee** [comment]
🔗 문제 링크
#169 

💡 풀이 사항
📆풀이 일자: 2024.01.30
⏰풀이 시간: 14분
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: 구현

✍ 풀이 방법
- 1부터 시작해서 tmp 값을 1씩 늘리면서 N이 tmp로 나눠지면서 tmp 값이 C보다 작을 때까지 해당 작업을 반복적으로 실행해준다.
- tmp 값 중 가장 큰 값을 R 값으로 설정한다.
- RxC 배열을 선언해준 후 문자열의 문자를 순차적으로 저장한다.
- 배열을 열 순서대로 읽어서 암호를 해독한다.

**Comment by ensk26** [comment]
https://github.com/Hanbat-Algo-Study/algorithm/pull/179

💡 풀이 사항
📆풀이 일자: 2024.01.29
⏰풀이 시간: 20분
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: 구현

✍ 풀이 방법
r,c를 입력받은 문자열의 길이 제곱근 부터 길이에 나눠떨어지는 가장큰 수를 r로 잡고 나머지를 c로 했다.
// 열 기준 배열을 입력받고 행 순으로 출력을 했다.
