### ISSUE TITLE
[브론즈1] 3985.롤 케이크

### ISSUE THREAD

**Issue by skdudddl** [Hanbat-Algo-Study/algorithm#110]
🔗 문제 링크
https://www.acmicpc.net/problem/3985

💡 풀이 사항
📆풀이 일자: 2024.00.00
⏰풀이 시간: 00분 00초
✨채점 결과: 오답🙅‍♀️🙅‍♂️/시간 초과⌛/런타임 에러⏱/정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등

✍ 풀이 방법
(풀이 접근 및 방법에 대한 설명)

**Comment by GeonHui2** [comment]
### 🔗 문제 링크
#138 

### 💡 풀이 사항
📆풀이 일자: 2024.01.27
⏰풀이 시간: 30분
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: 구현

### ✍ 풀이 방법
-잘라야 하는 번째 인덱스가 0이면 해당 인덱스를 넣어주고 카운트를 해주었다.
- 또한 시작 지점과 종료지점의 차를 구해서 기대 길이의 값을 구해주었다.

**Comment by skdudddl** [comment]
🔗 문제 링크
#153 

💡 풀이 사항
📆풀이 일자: 2024.01.27
⏰풀이 시간: 30분
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: 구현

✍ 풀이 방법

- P,K,cake, result 배열을 생성해주고 입력을 받는다.
- 입력받을 때 예상 max값을 구해준다.
- 그리고 숫자가 겹치지 않도록 cake가 false를 cake를 true로 만들어주고 그 값에 대한 result++(실제 max값을 구하기 위해)

**Comment by jisooolee** [comment]
🔗 문제 링크
#168 

💡 풀이 사항
📆풀이 일자: 2024.01.30
⏰풀이 시간: 15분
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: 구현

✍ 풀이 방법

- cake 조각을 갖게 되는 사람의 번호를 저장하는 cakes 배열을 생성한다.
- cake 조각을 가장 많이 원하는 사람의 정보를 저장하는 maxWants와 cake 조각을 실제로 가장 많이 갖게 되는 사람의 정보를 저장하는 maxGets 배열을 생성한다.
- 반복문을 돌면서 cakes 배열의 요소 값이 0이면 cakes 배열의 요소에 해당 조각을 갖게 되는 사람의 번호를 저장해준다.
- 각 사람마다 갖기를 원하는 케익 조각의 개수, 실제로 갖게 되는 케익 조각의 개수를 구해 max 값과 비교, max보다 클 경우에만 max에 값을 저장해준다.

**Comment by ensk26** [comment]
https://github.com/Hanbat-Algo-Study/algorithm/pull/179

💡 풀이 사항
📆풀이 일자: 2024.01.29
⏰풀이 시간: 20분
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: 구현

✍ 풀이 방법
선택하는 구역을 배열을 만들어 표시, 조각을 많이 선택하는 자와, 많이 선택된자를 비교 연산자로 구했다.
