### ISSUE TITLE
[브론즈2] 8320.직사각형을 만드는 방법

### ISSUE THREAD

**Issue by skdudddl** [Hanbat-Algo-Study/algorithm#112]
🔗 문제 링크
https://www.acmicpc.net/problem/8320

💡 풀이 사항
📆풀이 일자: 2024.00.00
⏰풀이 시간: 00분 00초
✨채점 결과: 오답🙅‍♀️🙅‍♂️/시간 초과⌛/런타임 에러⏱/정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등

✍ 풀이 방법
(풀이 접근 및 방법에 대한 설명)

**Comment by GeonHui2** [comment]
### 🔗 문제 링크
#140 

### 💡 풀이 사항
📆풀이 일자: 2024.01.27
⏰풀이 시간: 8분
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: 구현

### ✍ 풀이 방법
- 1과 자기 자신을 제외한 약수의 개수를 구해서 결괏값에 더해주었다.

**Comment by skdudddl** [comment]
🔗 문제 링크
#153

💡 풀이 사항
📆풀이 일자: 2024.01.27
⏰풀이 시간: 10분
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: 구현

✍ 풀이 방법

- 그림을 보면서 규칙이 뭐가 있는지 생각했다.
- n까지의 숫자의 약수의 갯수의 합을 알게되었고 반복문을 돌면서 더해주었다.

**Comment by ramrami-S** [comment]
🔗 문제 링크
#167 

💡 풀이 사항
📆풀이 일자: 2024.01.30
⏰풀이 시간: 14분 03초
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: 구현

✍ 풀이 방법
정사각형 N개가 주어졌을 때 직사각형을 만들 수 있는 경우의 수는 1부터 N까지의 수의 약수 조합에서 중복을 없앤 수와 같다.

ex N = 6 
1의 약수 - 1*1 
2의 약수 - 1*2 
3의 약수 - 1*3 
4의 약수 - 1*4 /  2*2
5의 약수 - 1*5 
6의 약수 - 1*6  / 2*3 => 모두 8개

1부터 N제곱근까지 수를 i라고 할 때, i부터 N까지 수 중에 i * j를 곱해도 N이 넘지 않으면 count++ 해준다.

**Comment by jisooolee** [comment]
🔗 문제 링크
#178

💡 풀이 사항
📆풀이 일자: 2024.01.30
⏰풀이 시간: 1시간...?
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: 구현

✍ 풀이 방법
- 1부터 n까지의 수, x를 순회하면서 각 수의 약수의 개수를 구했다.
- 중복을 방지하기 위해, x의 약수가 x의 제곱근보다 작거나 같을 때까지만 약수의 개수를 구하고, 구한 개수를 result에 더해주었다.
- 앞으로는 미루지 말아야겠다...
