### ISSUE TITLE
[브론즈2] 8958.OX 퀴즈

### ISSUE THREAD

**Issue by skdudddl** [Hanbat-Algo-Study/algorithm#113]
🔗 문제 링크
https://www.acmicpc.net/problem/8958

💡 풀이 사항
📆풀이 일자: 2024.00.00
⏰풀이 시간: 00분 00초
✨채점 결과: 오답🙅‍♀️🙅‍♂️/시간 초과⌛/런타임 에러⏱/정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등

✍ 풀이 방법
(풀이 접근 및 방법에 대한 설명)

**Comment by GeonHui2** [comment]
### 🔗 문제 링크
#140 

### 💡 풀이 사항
📆풀이 일자: 2024.01.27
⏰풀이 시간: 8분
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: 구현

### ✍ 풀이 방법
- 0일 경우 누적값에 +1을 하고 결괏값에 더해주었다.
- X 일 경우에는 누적값을 0으로 초기화해주었다.

**Comment by skdudddl** [comment]
🔗 문제 링크
#153

💡 풀이 사항
📆풀이 일자: 2024.01.27
⏰풀이 시간: 8분
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: 구현

✍ 풀이 방법

- O의 누적 개수를 더해주는 방식으로 구현했다.
- X가 나올 경우 cnt 을 0으로 초기화시켜 다시 누적을 구한다.

**Comment by ramrami-S** [comment]
🔗 문제 링크
#171 

💡 풀이 사항
📆풀이 일자: 2024.01.30
⏰풀이 시간: 09분 41초
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: 구현

✍ 풀이 방법
입력값이 O이면 점수를 업데이트 하고, 현재 점수를 +1 해준다. 그러다가 X를 만나면 현재 점수를 1로 초기화 해준다.

*주의할 것: 현재 점수 1로 초기화 하기
BufferdReader로 입력을 받았는데 계속 nullpointer (런타임 에러)가 발생했다. while 문으로 br.readLine()이 null일 때까지 입력 받는 것으로 고쳐서 해결했따 (-> 이 부분은 구글링 함)

**Comment by jisooolee** [comment]
🔗 문제 링크
#175

💡 풀이 사항
📆풀이 일자: 2024.01.30
⏰풀이 시간: 10분
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: 구현

✍ 풀이 방법
- boolean 변수 cont를 이용해 O가 연속적으로 등장했는지의 여부를 저장해준다.
- 만약 O가 연속적으로 등장했다면 cnt를 result에 더해주고 cnt 값을 1 증가해준다.
- 만약 X가 등장했다면 cnt를 0으로, cont를 false로 바꿔준다.
- X 다음으로 O가 등장했다면 cont를 true로 바꿔준다.

**Comment by ensk26** [comment]
https://github.com/Hanbat-Algo-Study/algorithm/pull/179

💡 풀이 사항
📆풀이 일자: 2024.01.29
⏰풀이 시간: 11분
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: 구현

✍ 풀이 방법
o일때는 연속적으로 점수가 올라가도록, x는 값을 0으로 초기화
