### ISSUE TITLE
[실버3] 17413.단위 뒤집기 2

### ISSUE THREAD

**Issue by skdudddl** [Hanbat-Algo-Study/algorithm#118]
🔗 문제 링크
https://www.acmicpc.net/problem/17413

💡 풀이 사항
📆풀이 일자: 2024.00.00
⏰풀이 시간: 00분 00초
✨채점 결과: 오답🙅‍♀️🙅‍♂️/시간 초과⌛/런타임 에러⏱/정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등

✍ 풀이 방법
(풀이 접근 및 방법에 대한 설명)

**Comment by jisooolee** [comment]
### 🔗 문제 링크
#148 

### 💡 풀이 사항
📆풀이 일자: 2024.01.28
⏰풀이 시간: 1시간 30분
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: 구현

### ✍ 풀이 방법
- 문자열 값이 <이면 isTag를 true로 isWord를 false로 설정해주었다.
- 문자열 값이 >이면 isTag를 false로 설정해주었다.
- isTag가 true일 땐 문자를 그대로 출력해주었다.
- isTag가 false이면서 단어일 땐 단어를 저장하는 word List에 문자 값을 저장해주었다.
- isTag가 false이면서 문자 값이 단어의 끝일 땐 역순으로 word를 출력해주었다.

**Comment by ramrami-S** [comment]
🔗 문제 링크
#164 

💡 풀이 사항
📆풀이 일자: 2024.01.30
⏰풀이 시간: 50분 10초
✨채점 결과: 시간 초과⌛
📃예상 문제 유형: 구현, 문자열 

✍ 풀이 방법
< 가 나오면 openTag를 true로 바꿔주고 >가 나오면 false로 바꿔준다
꺽쇠 안에 있는 문자들은 원래 순서대로 출력해주고,
openTag가 false일 때의 문자들은 모아뒀다가(?) 공백일 때, 입력 문자열이 끝났을 때 역순으로 출력해준다.

시간초과가 났는데.... 위에 우리 친구들이 올려준 내용을 보니 stack으로 풀 수 있는 것 같아서 풀어보려고 한다.
