### ISSUE TITLE
[실버2] 1260.DFS와 BFS

### ISSUE THREAD

**Issue by skdudddl** [Hanbat-Algo-Study/algorithm#180]
🔗 문제 링크
https://www.acmicpc.net/problem/1260

💡 풀이 사항
📆풀이 일자: 2024.00.00
⏰풀이 시간: 00분 00초
✨채점 결과: 오답🙅‍♀️🙅‍♂️/시간 초과⌛/런타임 에러⏱/정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등

✍ 풀이 방법
(풀이 접근 및 방법에 대한 설명)

**Comment by ensk26** [comment]
🔗 문제 링크
https://github.com/Hanbat-Algo-Study/algorithm/pull/190/files

💡 풀이 사항
📆풀이 일자: 2024.01.31
⏰풀이 시간: 20분
✨채점 결과: 정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: BFS/DFS

✍ 풀이 방법
- bfs, dfs를 이용해 푸는 문제
- ArrayList를 이용해 노드를 저장

**Comment by ramrami-S** [comment]
🔗 문제 링크
#191 

💡 풀이 사항
📆풀이 일자: 2024.01.31 (과 02.01 사이)
⏰풀이 시간: 30분
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: BFS/DFS

✍ 풀이 방법
- ArrayList로 그래프 표현 (인접 리스트)
- DFS 는 재귀, BFS는 큐로 풀었다 (스택으로도 하긴 했는데 출력이 이상해서 맑은 정신에서 다시 해 볼 예정)
- 자바로 큐 어떻게 쓰는지, 정렬 함수 정도 구글링 했다

**Comment by jisooolee** [comment]
🔗 문제 링크
#192 

💡 풀이 사항
📆풀이 일자: 2024.02.01
⏰풀이 시간: 1시간 45분
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: BFS/DFS

✍ 풀이 방법
- Map<Integer, ArrayList<Integer>> type을 이용해서 graph를 구현했다.
- Collections.sort를 이용해서 연결된 node를 크기 순으로 정렬해주었다.
- 처음 문제를 풀 때, 연결된 node 중 크기가 작은 것부터 탐색한다는 조건을 못 보아서 시간이 오래 걸렸다.
- 문제를 잘 읽어야지

**Comment by GeonHui2** [comment]
🔗 문제 링크
#217 

💡 풀이 사항
📆풀이 일자: 2024.02.04
⏰풀이 시간: 20분
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: BFS/DFS

✍ 풀이 방법
- 해당 정점과 연결된 다른 정점을 해당 정점의 ArrayList에 저장해 주었다.
- 정점 번호가 작은 것을 먼저 방문해야 돼서 먼저 정렬 후 V를 각각 BFS와 DFS를 통해서 문제를 구현했다.
- 매 경우를 print 할 경우 시간 복잡도가 증가하기 때문에 StringBuilder에 값을 추가해서 출력했다.

**Comment by skdudddl** [comment]
🔗 문제 링크
#205 

💡 풀이 사항
📆풀이 일자: 2024.02.03
⏰풀이 시간: 60분
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: DFS, BFS

✍ 풀이 방법

- bfs, dfs 다 까먹어서 다시 공부하고 하느라좀 걸렷다.
- dfs는 2차원배열의 재귀로 bfs는 큐로 풀었다.
