### ISSUE TITLE
[실버1] 2178.미로 탐색

### ISSUE THREAD

**Issue by skdudddl** [Hanbat-Algo-Study/algorithm#181]
🔗 문제 링크
https://www.acmicpc.net/problem/2178

💡 풀이 사항
📆풀이 일자: 2024.00.00
⏰풀이 시간: 00분 00초
✨채점 결과: 오답🙅‍♀️🙅‍♂️/시간 초과⌛/런타임 에러⏱/정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등

✍ 풀이 방법
(풀이 접근 및 방법에 대한 설명)

**Comment by ensk26** [comment]
🔗 문제 링크
https://github.com/Hanbat-Algo-Study/algorithm/pull/190/files#diff-8f1c3ee203d38b575b2a6026cacd8be12cda13238659f616837379c980c51c1c

💡 풀이 사항
📆풀이 일자: 2024.02.01
⏰풀이 시간: 30분 00초
✨채점 결과: 정답
📃예상 문제 유형: BFS

✍ 풀이 방법
- BFS를 이용해 탐색을 진행했다.

**Comment by ramrami-S** [comment]
🔗 문제 링크
#196 

💡 풀이 사항
📆풀이 일자: 2024.02.01
⏰풀이 시간: 30분 00초
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: BFS

✍ 풀이 방법
"최소의 칸"이라는 문구를 보고 BFS로 풀어야겠다고 생각하고 DFS로 풀어버렸다..ㅋㅋㅋㅋㅋ
시간초과가 났는데 BFS로 풀었다고 믿고 있었기 때문에 뭐가 틀렸는지 모르고 있다가
DFS인 것을 깨닫고 BFS로 바꿨는데 바로 정답!
~이래서 사람이 잠을 잘 자야 한다.~

**Comment by jisooolee** [comment]
🔗 문제 링크
#203 

💡 풀이 사항
📆풀이 일자: 2024.02.02
⏰풀이 시간: 2시간
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: BFS

✍ 풀이 방법
- BFS로 문제를 풀어야겠다고 생각하고서 아무 생각 없이 DFS로 구현해놓고 틀린 이유를 찾느라 1시간을 허비했다😢
- DFS로 구현하고 테스트 케이스가 잘 실행되는 것까지 확인했는데, 채점할 때 메모리초과 오류가 계속 발생했다.
- 이유를 못 찾겠어서 메모리초과 오류 힌트를 살짝 찾아봤다ㅎㅎ😊
- 현재 경로에서 갈 수 있는 다음 경로를 탐색할 때, 탐색한 경로의 값을 0으로 바꾸어 방문한 것을 표시해주어야 하는데, 표시를 안 해주어서 메모리초과가 난 것이었다.
- 코드를 수정해서 채점을 통과했다.

**Comment by GeonHui2** [comment]
🔗 문제 링크
#204 

💡 풀이 사항
📆풀이 일자: 2024.02.02
⏰풀이 시간: 1시간 30분
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: BFS

✍ 풀이 방법
- BFS 구현 방법을 잘 몰라서 문제를 풀다가 중간에 공부하면서 구현했다.
- 이전 위치의 값에서 1을 더한 값을 현재 위치에 저장하면서 1칸씩 이동했을 때 최소 이동 거리를 구현해서 문제를 해결했다.

**Comment by skdudddl** [comment]
🔗 문제 링크
#215 

💡 풀이 사항
📆풀이 일자: 2024.02.03
⏰풀이 시간: 40분
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: BFS

✍ 풀이 방법

- 제일 빠른 길이니 bfs로 구현했다.
- 미로탐색으로 진행했고 다음 좌표엔 현재 좌표의 값의+1을 해주면서 길이를 구해줬다.
