### ISSUE TITLE
[실버1] 2667. 단지번호붙이기

### ISSUE THREAD

**Issue by skdudddl** [Hanbat-Algo-Study/algorithm#183]
🔗 문제 링크
https://www.acmicpc.net/problem/2667

💡 풀이 사항
📆풀이 일자: 2024.00.00
⏰풀이 시간: 00분 00초
✨채점 결과: 오답🙅‍♀️🙅‍♂️/시간 초과⌛/런타임 에러⏱/정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등

✍ 풀이 방법
(풀이 접근 및 방법에 대한 설명)

**Comment by ensk26** [comment]
🔗 문제 링크
https://github.com/Hanbat-Algo-Study/algorithm/pull/197

💡 풀이 사항
📆풀이 일자: 2024.02.02
⏰풀이 시간: 20분 00초
✨채점 결과: 정답
📃예상 문제 유형: BFS

✍ 풀이 방법
- bfs를 이용해 단지별 개수를 구해 넘겨주었다.
- 해당 개수를 list에 담아 정렬하고, list 길이를 출력했다.

**Comment by ramrami-S** [comment]
🔗 문제 링크
#207 

💡 풀이 사항
📆풀이 일자: 2024.02.03
⏰풀이 시간: ?? (어제 밤에 풀다가 잠들었는데 오늘 살짝 더 수정해서 맞춤)
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: BFS

✍ 풀이 방법
(0,0)부터 (N-1,N-1)까지 탐색 하면서 값이 1인 경우 BFS를 시작한다. 시작한 아파트에서 갈 수 있는 아파트의 수를 세서 nums 배열에 저장한다.
BFS를 빠져나오면 이어서 탐색을 하는데 visited에 true로 표시된 좌표는 이미 탐색한 아파트이므로 지나간다
BFS를 시작한 횟수가 단지 수이고 BFS를 돌면서 카운트한 수가 아파트 수이다.
마지막에 단지 수와 아파트 수를 저장한 배열을 정렬해서 프린트 하면 정답

**Comment by jisooolee** [comment]
🔗 문제 링크
#210 

💡 풀이 사항
📆풀이 일자: 2024.02.03
⏰풀이 시간: 32분
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: DFS

✍ 풀이 방법
- (N+2)x(N+2) 배열을 만들어 아파트 정보를 저장했다.
- N * N / 2 + 1 크기의 배열 cnts을 만들어 아파트 단지 별 아파트 개수를 저장해주었다.
- 배열의 요소를 하나씩 탐색하다가 1을 만나면 해당 위치에서부터 DFS를 진행했다.
- DFS를 진행한 후 탐색한 요소의 개수를 return하고 반환받은 값을 cnts에 저장해주었다.
- 단지 별 아파트 개수를 오름차순으로 출력해야한다는 조건을 못 봐서 세 번 정도 틀렸다...
- 문제를 꼼꼼하게 읽어야겠다.

**Comment by GeonHui2** [comment]
🔗 문제 링크
#210 

💡 풀이 사항
📆풀이 일자: 2024.02.03
⏰풀이 시간: 30분
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: BFS

✍ 풀이 방법
- 해당 인덱스의 값이 1이면 BFS를 활용해서 주변이 아파트인 경우를 카운트해서 결괏값에 넣어주었다.
- 사방 탐색을 통해 해당 인덱스의 값이 1이면 Queue에 저장 후 인덱스 값을 0으로 변경하였다.

**Comment by skdudddl** [comment]
🔗 문제 링크
#215 

💡 풀이 사항
📆풀이 일자: 2024.02.02
⏰풀이 시간: 30분
✨채점 결과: 정답
📃예상 문제 유형: BFS

✍ 풀이 방법

- bfs 를 이용한 미로탐색으로 구현했다.
- 각 배열에 저장한 후 sort를 이용해서 정렬 후 출력한다.
