### ISSUE TITLE
[실버2] 1012. 유기농 배추

### ISSUE THREAD

**Issue by ramrami-S** [Hanbat-Algo-Study/algorithm#185]
🔗 문제 링크
https://www.acmicpc.net/problem/1012

💡 풀이 사항
📆풀이 일자: 2024.00.00
⏰풀이 시간: 00분 00초
✨채점 결과: 오답🙅‍♀️🙅‍♂️/시간 초과⌛/런타임 에러⏱/정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등

✍ 풀이 방법
(풀이 접근 및 방법에 대한 설명)

**Comment by ensk26** [comment]
🔗 문제 링크
https://github.com/Hanbat-Algo-Study/algorithm/pull/198

💡 풀이 사항
📆풀이 일자: 2024.02.02
⏰풀이 시간: 30분
✨채점 결과: 정답
📃예상 문제 유형: BFS

✍ 풀이 방법
- 배열을 만들어 배추가 심겨있는 곳을 표시하고 bfs를 이용해 배추벌레가 필요한 구간을 구했다.

**Comment by jisooolee** [comment]
🔗 문제 링크
#212 

💡 풀이 사항
📆풀이 일자: 2024.02.03
⏰풀이 시간: 15분
✨채점 결과: 정답
📃예상 문제 유형: DFS

✍ 풀이 방법
- 이중 배열 map을 생성해 배추의 위치를 저장해주었다.
- 배열을 탐색하면서 1을 발견하면 DFS를 진행해 배추 영역을 탐색하고, 탐색한 위치는 0으로 표시해주었다.
- 탐색을 진행할때마다 cnt 값을 1 증가해주었다.

**Comment by ramrami-S** [comment]
🔗 문제 링크
#213 

💡 풀이 사항
📆풀이 일자: 2024.02.03
⏰풀이 시간: ??
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: BFS

✍ 풀이 방법
배추 밭을 0,0부터 N-1, M-1까지 돌면서 방문한 적 없는 배추가 있는 곳이면 BFS를 시작한다. (앞선 아파트 문제와 유사)
BFS를 돌면서 방문하는 곳을 true로 바꿔준다.
BFS를 시작하는 횟수를 카운트 해서 정답으로 제출!
 
*입력 받을 때 M, N, K를 static으로 선언해 놓고 main 함수 안에서 다시 int로 선언하는 바보같은 실수를 했따.... 
그걸 모르고 디버깅을 해도 출력을 찍어봐도 답이 왜 틀렸는지 모르겠어서 많이 헤멨다..........

**Comment by GeonHui2** [comment]
🔗 문제 링크
#206 

💡 풀이 사항
📆풀이 일자: 2024.02.03
⏰풀이 시간: 30분
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: BFS


✍ 풀이 방법
- BFS를 활용해서 문제를 해결했다.
- 1번 컴퓨터를 기준으로 해당 컴퓨터를 방문하지 않고 네트워크 연결이 되어 있는 경우 Queue에 넣어서 문제를 해결했다.

**Comment by skdudddl** [comment]
🔗 문제 링크
#215 

💡 풀이 사항
📆풀이 일자: 2024.02.03
⏰풀이 시간: 20분
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: BFS

✍ 풀이 방법

- 2차원 배열에 입력받아서 bfs로 풀었다.
- 문제에서의 x, y와 내가 생각하는 x,y 는 달라서 좀 헷갈렸다.
- 4방탐색으로 통해 count를 셌다.
