### ISSUE TITLE
[실버1] 1697. 숨바꼭질

### ISSUE THREAD

**Issue by ramrami-S** [Hanbat-Algo-Study/algorithm#186]
🔗 문제 링크
https://www.acmicpc.net/problem/1697

💡 풀이 사항
📆풀이 일자: 2024.00.00
⏰풀이 시간: 00분 00초
✨채점 결과: 오답🙅‍♀️🙅‍♂️/시간 초과⌛/런타임 에러⏱/정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등

✍ 풀이 방법
(풀이 접근 및 방법에 대한 설명)

**Comment by ensk26** [comment]
🔗 문제 링크
https://github.com/Hanbat-Algo-Study/algorithm/pull/199

💡 풀이 사항
📆풀이 일자: 2024.02.02
⏰풀이 시간: 60분
✨채점 결과: 정답
📃예상 문제 유형: BFS

✍ 풀이 방법
- 방문한 좌표는 다시 안 가도록 체크해서 필요한 만큼만 만들어지도록 해야 한다.
- 각 거리 이동의 조건으로 좌표를 이동하고, 시간을 더해 빨리 도착하는 시간을 구했다.

**Comment by GeonHui2** [comment]
🔗 문제 링크
#211 

💡 풀이 사항
📆풀이 일자: 2024.02.03
⏰풀이 시간: 20분
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: BFS


✍ 풀이 방법
- 방문 처리 배열을 갈 수 있는 최대 값인 100000까지 만들었다.
- 해당 위치를 기준으로 위치 - 1, 위치 + 1, 위치 * 2한 경우를 모두 Queue에 넣고 cnt + 1을 했다.
- 해당 위치가 K가 될 때까지 탐색하도록 구현했다.

**Comment by jisooolee** [comment]
🔗 문제 링크
#220 

💡 풀이 사항
📆풀이 일자: 2024.02.04
⏰풀이 시간: 2시간 안 되게 걸린 것 같다
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: BFS


✍ 풀이 방법
- 처음에는 단순 구현으로 풀었는데 틀렸다.
- BFS로 다시 풀었는데 또 틀렸다.
- 방문할 위치를 저장할 hasToVisit 큐에 depth를 함께 저장해야 한다는 힌트를 얻고 다시 BFS를 구현해서 풀었다.

**Comment by ramrami-S** [comment]
🔗 문제 링크
#225 

💡 풀이 사항
📆풀이 일자: 2024.02.06
⏰풀이 시간: 2시간 넘음
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: BFS

✍ 풀이 방법
1. BFS로 모든 경우를 고려(+1, -1, *2 하는 경우 단,  직전에 +1을 했다면 -1을 하지 않고, 직전에 -1을 했다면 +1을 하지 않도록 했다)해서 목표값이 나오면 멈추고 가장 최소 연산을 했을 때 연산 횟수를 정답으로 출력하도록 코드를 작성했다.
2. 메모리 초과가 났다.
3. 가지치기1) 연산과 결과값을 출력해보니 음수도 있었고, K의 MAX값(100,000인가?)을 넘는 수도 있었다. 이런 수들은 고려하지 않도록 해줬다
4. 가지치기2) 찾아본 반례를 실행해 봤을 때 3번까지 해줘도 출력이 엄청나게 많이 됐다 출력을 보다 보니 똑같은 결과값들이 많이 나오는 것을 볼 수 있었다. -> 같은 결과값이 나왔을 때 그 값이 나오기까지의 최소 연산만 기억한다. ex) 5 + 1 = 6 / 2 * 2 + 1 + 1 = 6 이런 식으로 같은 결과 값이 다른 연산 횟수로 나올 수 있는데 더 작은 연산 횟수만 기억한다면 K까지 도달 했을 때, K를 만들기 위한 최소 연산 수를 출력할 수 있다!

반례들
3482 45592 => 637
1 100000 => 21
15964 89498 => 4781
10007 98767 => 2343

**Comment by skdudddl** [comment]
🔗 문제 링크
#236 

💡 풀이 사항
📆풀이 일자: 2024.02.05
⏰풀이 시간: 하루 이상
✨채점 결과: 정답
📃예상 문제 유형: BFS

✍ 풀이 방법

- bfs를 이용해서 구현했다.
- next가 0 이상 100001이하의 조건을 넣어서 풀었다.
