### ISSUE TITLE
[실버2] 11724. 연결 요소의 개수

### ISSUE THREAD

**Issue by ramrami-S** [Hanbat-Algo-Study/algorithm#187]
🔗 문제 링크
https://www.acmicpc.net/problem/11724

💡 풀이 사항
📆풀이 일자: 2024.00.00
⏰풀이 시간: 00분 00초
✨채점 결과: 오답🙅‍♀️🙅‍♂️/시간 초과⌛/런타임 에러⏱/정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등

✍ 풀이 방법
(풀이 접근 및 방법에 대한 설명)

**Comment by ensk26** [comment]
🔗 문제 링크
https://github.com/Hanbat-Algo-Study/algorithm/pull/200

💡 풀이 사항
📆풀이 일자: 2024.02.02
⏰풀이 시간: 00분 00초
✨채점 결과: 정답
📃예상 문제 유형: BFS

✍ 풀이 방법
- 그래프를 만들고, bfs를 이용해 그룹이 몇 개인지 구했다.

**Comment by ramrami-S** [comment]
🔗 문제 링크
#213 (배추랑 같이 있음)

💡 풀이 사항
📆풀이 일자: 2024.02.03
⏰풀이 시간: 10분컷
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: DFS

✍ 풀이 방법
인접리스트로 그래프를 표현한 뒤 방문하지 않는 노드를 돌면서 그 노드의 자식을 순회한다 (dfs)
dfs를 도는 횟수를 카운트 해서 정답으로 제출!
*이전 문제들과 비슷한데 계속 bfs를 했어서 이번엔 dfs로 해봤다.

**Comment by GeonHui2** [comment]
🔗 문제 링크
#214 

💡 풀이 사항
📆풀이 일자: 2024.02.03
⏰풀이 시간: 1시간 40분
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: DFS

✍ 풀이 방법
- 처음에는 BFS로 풀려고 했지만 40%에서 틀려서 계속 고민했다.
- 고민해도 어느 부분이 문제인지 잘 몰라서 이전에 파이썬으로 풀었던 방식과 하람 누나가 풀었던 방법을 참고해서 문제를 구현했다.
- 해당 인덱스에 연결된 노드를 저장 후 방문 노드를 true로 변경했다.

**Comment by jisooolee** [comment]
🔗 문제 링크
#221 

💡 풀이 사항
📆풀이 일자: 2024.02.04
⏰풀이 시간: 33분
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: DFS

✍ 풀이 방법
- DFS로 모든 그래프를 탐색해주었다.
- DFS로 그래프를 탐색할 때 방문한 노드의 개수를 반환해주고, N에서 그 값을 빼주었다.
- 1번 노드부터 탐색을 시작해서 탐색을 시작할 root 노드의 번호를 1씩 증가해주면서 N 값이 0이 될 때까지 DFS 탐색을 진행해주었다.

**Comment by skdudddl** [comment]
🔗 문제 링크
#215 

💡 풀이 사항
📆풀이 일자: 2024.02.03
⏰풀이 시간:  20분
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: DFS

✍ 풀이 방법

- 2차원배열을 만들어서 그 좌표값에 true로 받는다.
- dfs로 그 배열을 탐색했다.
