### ISSUE TITLE
[실버1] 2468. 안전 영역

### ISSUE THREAD

**Issue by ramrami-S** [Hanbat-Algo-Study/algorithm#188]
🔗 문제 링크
https://www.acmicpc.net/problem/2468

💡 풀이 사항
📆풀이 일자: 2024.00.00
⏰풀이 시간: 00분 00초
✨채점 결과: 오답🙅‍♀️🙅‍♂️/시간 초과⌛/런타임 에러⏱/정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등

✍ 풀이 방법
(풀이 접근 및 방법에 대한 설명)

**Comment by ensk26** [comment]
🔗 문제 링크
https://github.com/Hanbat-Algo-Study/algorithm/pull/201

💡 풀이 사항
📆풀이 일자: 2024.02.02
⏰풀이 시간: 40분 00초
✨채점 결과: 정답
📃예상 문제 유형: BFS

✍ 풀이 방법
- 비 오는 높이를 마다 bfs를 이용해 안전 구역을 구했다.
- 비가 안 오는 경우도 고려해야 한다.

**Comment by GeonHui2** [comment]
🔗 문제 링크
#214 

💡 풀이 사항
📆풀이 일자: 2024.02.04
⏰풀이 시간: 1시간
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: BFS

✍ 풀이 방법
- 인덱스의 값을 배열에 넣어줄 때 최고 높이를 저장했다.
- 최대 높이까지 반복문을 통해서 모든 경우의 수를 확인했다.
- 해당 높이일 때 BFS를 통해서 안전한 영역의 수를 구했다.
- 해당 인덱스를 기준으로 4방 탐색이 아닌 좌, 하만 구현해서 해결하는 데 시간이 오래 걸렸다.
- 사방 탐색을 통해서 범위를 벗어나지 않고 방문하지 않고 기준 높이보다 높으면 Queue에 저장 후 방문 처리해주었다.
- 해당 높이의 안전 영역의 수와 결괏값의 최댓값을 결괏값에 저장해 주었다.

**Comment by ramrami-S** [comment]
🔗 문제 링크
#222 

💡 풀이 사항
📆풀이 일자: 2024.02.05
⏰풀이 시간: 25분
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: DFS

✍ 풀이 방법
- 가장 높은 높이를 찾고 0부터 가장 높은 높이까지의 안전 영역 중 가장 큰 값을 찾는다. (비가 안올수도? 있으므로 0부터 시작한다)
- 안전 영역은 0,0부터 N-1, N-1까지 순회하며 방문하지 않았거나 안전한 영역이면 cnt를 1씩 더해주고 dfs를 돌아서 순회할 수 있는 모든 영역에 visited를 표시하도록 한다 -> 여기서 N-1, N-1까지 모두 순회 했을 때 cnt 값이 안전영역의 개수!

**Comment by jisooolee** [comment]
🔗 문제 링크
#223 

💡 풀이 사항
📆풀이 일자: 2024.02.05
⏰풀이 시간: 나눠 풀어서 잘 모르겠지만 약 1시간...
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: DFS

✍ 풀이 방법
- 입력 받은 지역의 높이를 저장하는 Set을 만들고, 입력을 전부 받은 후 Set을 ArrayList로 만든 다음 오름차순으로 정렬해주었다.
- 각 높이 별 해당하는 지역의 개수를 저장하는 heightCnt 배열을 생성하고, map을 순회하면서 개수를 세주었다.
- DFS를 이용해 가장 작은 높이부터 안전지역의 개수를 구해주었다.

**Comment by skdudddl** [comment]
🔗 문제 링크
#219 

💡 풀이 사항
📆풀이 일자: 2024.02.04
⏰풀이 시간: 40분 00초
✨채점 결과: 정답
📃예상 문제 유형: BFS

✍ 풀이 방법

- 1부터 N까지의 높이에서 안전지대를 구해서 max값을 계속 구해줬다.
- 안전지대를 구할 때 bfs를 통해 구했다.
