### ISSUE TITLE
[골드5] 7576. 토마토

### ISSUE THREAD

**Issue by ramrami-S** [Hanbat-Algo-Study/algorithm#226]
🔗 문제 링크
https://www.acmicpc.net/problem/7576

💡 풀이 사항
📆풀이 일자: 2024.00.00
⏰풀이 시간: 00분 00초
✨채점 결과: 오답🙅‍♀️🙅‍♂️/시간 초과⌛/런타임 에러⏱/정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등

✍ 풀이 방법
(풀이 접근 및 방법에 대한 설명)

**Comment by ramrami-S** [comment]
🔗 문제 링크
#237 

💡 풀이 사항
📆풀이 일자: 2024.02.07
⏰풀이 시간: 오늘 강의 중간 중간.. 아마 합치면 2시간 정도?
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: BFS

✍ 풀이 방법
토마토 클래스를 만들어서 토마토의 좌표, 익은 날짜, 상태값을 저장한다. 최초의 익은 토마토를 큐에 넣고 (이때 익은 날은 0으로 함)
익지 않은 토마토를 순회하며 토마토를 익게 만드는 BFS를 돈다.
BFS에 끝난 다음 토마토가 모두 익으려면 몇 일이 되어야 하는지 파악하기 위해 박스 배열을 돌면서 토마토를 살핀다
여기서 익지 않은 토마토가 있다면 -1을 출력해 주도록 하고, 아니라면 박스에 담긴 토마토가 모두 익을 수 있는 날짜(익은 날짜의 최대값)를 찾는다.

*계속 메모리 초과가 나서 머리 아팠는데 bfs를 돌 때 큐에 넣을 때가 아닌 꺼내면서 방문을 체크해주면 큐가 쌓여서 메모리 초과의 원인이 될 수 있다고 한다!! -> 오늘 강의 시간에 풀었던 섬의 개수 문제에서 동일한 문제를 겪고 해결해 준 뒤 토마토 문제도 해결했다.

**Comment by skdudddl** [comment]
🔗 문제 링크
#239 

💡 풀이 사항
📆풀이 일자: 2024.02.07
⏰풀이 시간: 50분
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: BFS

✍ 풀이 방법

- 처음에 1이 하나만 있다고 보고 bfs로 구현했다.
- 그런데 테케 중에 하나가 1이 두개가 있어서 어떻게 해야하나 고민했다.
- 그래서 방문유무를 따지는 것이기 때문에 1이 나오면 q에 넣어주고 bfs를 돌려주는 쪽으로 구현했다.
- 그래서 함수를 따로 돌리지 않고 그냥 메인문에 넣었다.

**Comment by ensk26** [comment]
🔗 문제 링크
https://github.com/Hanbat-Algo-Study/algorithm/pull/241

💡 풀이 사항
📆풀이 일자: 2024.02.08
⏰풀이 시간: 120분
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: BFS

✍ 풀이 방법

- bfs를 이용해, 익은 토마토 기준으로 값을 채웠다.
- 만약 0이 있으면, 다 안익은것으로 -1을 출력, 값을 채우기 전에 0이 없으면 0을 출력해주었다.
- bfs를 하면서 최대 날짜를 구했다.

**Comment by jisooolee** [comment]
🔗 문제 링크
#253 

💡 풀이 사항
📆풀이 일자: 2024.02.10
⏰풀이 시간: 30분
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: BFS

✍ 풀이 방법
- 익은 토마토의 위치와 전체 토마토의 개수를 구했다.
- 익은 토마토의 위치를 hasToVisit 큐에 넣어주고 BFS 탐색을 진행하였다.
- 탐색 후 익은 토마토의 개수와 전체 토마토의 개수를 비교해, 익은 토마토 개수가 더 적을 경우에는 -1을, 반대의 경우에는 토마토가 전부 익는 데 걸린 일수를 출력해주었다.

**Comment by GeonHui2** [comment]
🔗 문제 링크
#257 

💡 풀이 사항
📆풀이 일자: 2024.02.07
⏰풀이 시간: 50분
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: BFS

✍ 풀이 방법
- 배열을 완성하면서 1인 구역은 따로 저장 후 BFS를 실행할 때 해당 구역들을 queue에 넣어줬다.
- 사방탐색을 통해서 해당 구역이 0인 부분이 있으면 기준 구역의 값에서 +1을 해주었다.
- 모든 배열을 확인하면서 0인 구간이 있으면 -1을 출력했고 결과값을 계속 비교해주면서 출력할 때는 -1 해서 출력했다.
