### ISSUE TITLE
[골드5] 14502. 연구소 

### ISSUE THREAD

**Issue by ramrami-S** [Hanbat-Algo-Study/algorithm#227]
🔗 문제 링크
https://www.acmicpc.net/problem/14502

💡 풀이 사항
📆풀이 일자: 2024.00.00
⏰풀이 시간: 00분 00초
✨채점 결과: 오답🙅‍♀️🙅‍♂️/시간 초과⌛/런타임 에러⏱/정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등

✍ 풀이 방법
(풀이 접근 및 방법에 대한 설명)

**Comment by ramrami-S** [comment]
🔗 문제 링크
#238 

💡 풀이 사항
📆풀이 일자: 2024.02.06
⏰풀이 시간: 1시간?
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: 조합 + BFS

✍ 풀이 방법
벽을 3개만 세우면 되므로 벽을 세울 수 있는 모든 경우의 수에서 BFS를 돌려서 바이러스가 최소로 퍼지는 영역?을 알아낸다.
조합은 재귀로 BFS는 큐로 구현

**Comment by skdudddl** [comment]
🔗 문제 링크
#239 

💡 풀이 사항
📆풀이 일자: 2024.02.06
⏰풀이 시간: 2시간
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: BFS

✍ 풀이 방법

- 정말 처음에 어떻게 풀어야할지 감이 안 와서 하람언니가 알려준 조합 + BFS로 풀려고 했다.
- 원래는 조합으로 풀고 bfs돌려줬다. 근데 이제 원상복귀를 해줬다.
- mapcopy를 만들어주고 그걸로 count 세주는 방법으로 했다.

**Comment by ensk26** [comment]
🔗 문제 링크
https://github.com/Hanbat-Algo-Study/algorithm/pull/242

💡 풀이 사항
📆풀이 일자: 2024.02.06
⏰풀이 시간: 1시간
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: 조합 + BFS

✍ 풀이 방법
- 벽을 3개를 두는 경우를 재귀를 이용해 조합을 만들고, bfs로 안전구역을 구했다.

**Comment by GeonHui2** [comment]
🔗 문제 링크
#233 

💡 풀이 사항
📆풀이 일자: 2024.02.06
⏰풀이 시간: 1시간
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: BFS

✍ 풀이 방법
- 6중 for문을 사용해서 벽을 세울 수 있는 모든 경우의 수를 구했다.
- BFS를 통해서 바이러스가 퍼지고 남은 안전한 구역의 수를 카운트 후 안전 영역의 최대 크기를 구했다.

**Comment by jisooolee** [comment]
🔗 문제 링크
#254 

💡 풀이 사항
📆풀이 일자: 2024.02.06
⏰풀이 시간: 기억이 안 난다
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: BFS

✍ 풀이 방법
- 조합을 이용해 벽을 세울 위치를 구했다.
- 벽을 다 세우면 BFS 탐색을 이용해 안전지역의 개수를 구했다.
- 모든 경우의 수를 탐색하고, 그 중 안전지역의 개수가 가장 큰 경우를 답으로 출력하였다.
