### ISSUE TITLE
[골드4] 10026. 적록색약 

### ISSUE THREAD

**Issue by ramrami-S** [Hanbat-Algo-Study/algorithm#228]
🔗 문제 링크
https://www.acmicpc.net/problem/10026

💡 풀이 사항
📆풀이 일자: 2024.00.00
⏰풀이 시간: 00분 00초
✨채점 결과: 오답🙅‍♀️🙅‍♂️/시간 초과⌛/런타임 에러⏱/정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등

✍ 풀이 방법
(풀이 접근 및 방법에 대한 설명)

**Comment by ensk26** [comment]
🔗 문제 링크
https://github.com/Hanbat-Algo-Study/algorithm/pull/244

💡 풀이 사항
📆풀이 일자: 2024.02.08
⏰풀이 시간: 40분
✨채점 결과: 정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: BFS

✍ 풀이 방법
- bfs와 적록 색약 bfs를 만들어 그룹의 개수를 구했다.

**Comment by GeonHui2** [comment]
🔗 문제 링크
#240 

💡 풀이 사항
📆풀이 일자: 2024.02.07
⏰풀이 시간: 40분
✨채점 결과: 정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: BFS

✍ 풀이 방법
- 적록색약이 아닌 사람이 봤을 때를 기준으로 각 색상을 BFS를 통해 구역을 구했다.
- 적록색약이 아닌 사람을 확인 할 때 R인 구역을 G로 변경해주었다.
- 변경 후 적록색약인 사람을 기준으로 BFS를 통해 구역을 구했다.

**Comment by ramrami-S** [comment]
🔗 문제 링크
#249 ("섬의 개수"랑 같이 있음)

💡 풀이 사항
📆풀이 일자: 2024.02.09
⏰풀이 시간: 10분
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: DFS

✍ 풀이 방법
전부 다 탐색 해야 하는 경우여서 코드가 간단한 DFS(재귀로 구현)를 선택했다.
적록색약이 아닌 사람의 경우 R, G, B 모든 경우에 탐색을 시작하고 적록색약인 경우 R이거나 G, B인 경우에 탐색을 시작한다.
탐색을 시작한 색깔 정보를 파라미터로 주어서 같은 색깔을 만나면 방문 표시를 체크하는 방식으로 DFS를 구현했고,
적록색약이 아닌 사람과 적록색약인 사람의 경우에 탐색을 시작하는 횟수를 카운트해서 정답으로 출력!

**Comment by jisooolee** [comment]
🔗 문제 링크
#246 

💡 풀이 사항
📆풀이 일자: 2024.02.09
⏰풀이 시간: 25분
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: BFS

✍ 풀이 방법
- 적록 색약인 사람과 적록 색약이 아닌 사람의 경우를 나누어 BFS 탐색을 해주었다.
