### ISSUE TITLE
[골드5] 7569. 토마토 (중복x) 

### ISSUE THREAD

**Issue by ramrami-S** [Hanbat-Algo-Study/algorithm#229]
🔗 문제 링크
https://www.acmicpc.net/problem/7569

💡 풀이 사항
📆풀이 일자: 2024.00.00
⏰풀이 시간: 00분 00초
✨채점 결과: 오답🙅‍♀️🙅‍♂️/시간 초과⌛/런타임 에러⏱/정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등

✍ 풀이 방법
(풀이 접근 및 방법에 대한 설명)

**Comment by jisooolee** [comment]
🔗 문제 링크
#240 

💡 풀이 사항
📆풀이 일자: 2024.02.07-08
⏰풀이 시간: 약 1시간 20분?
✨채점 결과: 정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: BFS

✍ 풀이 방법
- BFS를 이용해서 익은 토마토 주변의 안 익은 토마토를 탐색해주었다.
- 탐색 과정에서 안 익은 토마토 개수를 세서 전체 토마토 대비 안 익은 토마토 개수가 더 적으면 -1을, 탐색 시작 전 익은 토마토의 개수와 전체 토마토 개수가 같으면 0을, 그 외에는 탐색 횟수를 출력해주었다.

**Comment by ensk26** [comment]
🔗 문제 링크
https://github.com/Hanbat-Algo-Study/algorithm/pull/251

💡 풀이 사항
📆풀이 일자: 2024.02.10
⏰풀이 시간: 30분
✨채점 결과: 정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: BFS

✍ 풀이 방법

- bfs로 토마토가 익는데 걸리는 기간을 구했다.
- 입력시 익은 토마토와, 토마토가 아닌 개수를 구해,  이미 전부 익은 경우와, 다 안익은 경우를 구분해 주었다.

**Comment by ramrami-S** [comment]
🔗 문제 링크
#255 

💡 풀이 사항
📆풀이 일자: 2024.02.10
⏰풀이 시간: 40분
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: BFS

✍ 풀이 방법
2차원 배열의 토마토 문제와 동일하게 토마토 클래스로 좌표, 익은 날짜, 토마토 상태를 저장해 주었다.
처음에 익은 토마토를 큐에 넣어준 뒤 BFS를 돌고 나서 토마토가 모두 익으려면 걸리는 날짜를 찾는다 (토마토 박스에 있는 토마토 중 가장 높은 익은 날짜를 찾으면 됨)

단, 모든 토마토가 익었을 경우와 BFS를 모두 돌고 나서도 익지 못한 토마토가 있는 경우는 별도로 처리했다. (입력값을 받을 때 모든 토마토가 익어 있다면 바로 0을 출력하고 프로그램을 종료한다, BFS 이후 탐색 이후 익지 못한 토마토를 발견하면 바로 반목문을 종료하고 -1을 출력한다)

**Comment by GeonHui2** [comment]
🔗 문제 링크
#258 

💡 풀이 사항
📆풀이 일자: 2024.02.12
⏰풀이 시간: 50분
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: BFS

✍ 풀이 방법
- 이전 토마토 문제와 동일한 방식으로 구현했다.
- 위, 아래, 왼쪽, 오른쪽, 앞, 뒤 여섯 방향 확인하기 위해서 높이도 추가해줬다.

**Comment by skdudddl** [comment]
🔗 문제 링크
#260 

💡 풀이 사항
📆풀이 일자: 2024.02.12
⏰풀이 시간: 약 1시간
✨채점 결과: 정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: BFS

✍ 풀이 방법

- 여기서는 3차원 배열로 만들어서 풀었다.
- 미로탐색에서 위아래로 가는 방향을 추가했다.
- 첫번째에 풀었던 토마토 로직을 따라 구현했다.
