### ISSUE TITLE
[실버2] 4963. 섬의 개수 

### ISSUE THREAD

**Issue by ramrami-S** [Hanbat-Algo-Study/algorithm#230]
🔗 문제 링크
https://www.acmicpc.net/problem/4963

💡 풀이 사항
📆풀이 일자: 2024.00.00
⏰풀이 시간: 00분 00초
✨채점 결과: 오답🙅‍♀️🙅‍♂️/시간 초과⌛/런타임 에러⏱/정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등

✍ 풀이 방법
(풀이 접근 및 방법에 대한 설명)

**Comment by jisooolee** [comment]
🔗 문제 링크
#234 

💡 풀이 사항
📆풀이 일자: 2024.02.07
⏰풀이 시간: 30분
✨채점 결과: 정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: DFS

✍ 풀이 방법
- 섬의 좌표를 전부 확인하면서 값이 1일 경우 DFS로 전체 섬의 위치를 표시해주었다.

**Comment by GeonHui2** [comment]
🔗 문제 링크
#235 

💡 풀이 사항
📆풀이 일자: 2024.02.07
⏰풀이 시간: 25분
✨채점 결과: 정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: BFS

✍ 풀이 방법
- w, h의 입력값이 0 0이 아닐 때 까지 반복문을 돌렸다.
- 섬의 좌표를 확인해서 1인 경우에 BFS를 통해 섬의 수를 구했다.

**Comment by skdudddl** [comment]
🔗 문제 링크
#239 

💡 풀이 사항
📆풀이 일자: 2024.02.07
⏰풀이 시간: 30분
✨채점 결과: 정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: BFS

✍ 풀이 방법

- 8방 탐색으로 bfs 로 풀었다.

**Comment by ensk26** [comment]
🔗 문제 링크
https://github.com/Hanbat-Algo-Study/algorithm/pull/243

💡 풀이 사항
📆풀이 일자: 2024.02.07
⏰풀이 시간: 30분
✨채점 결과: 정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: BFS

✍ 풀이 방법

- bfs를 이용해 갈 수 있는 섬을 그룹을 만들어 개수를 구했다.

**Comment by ramrami-S** [comment]
🔗 문제 링크
#249 

💡 풀이 사항
📆풀이 일자: 2024.02.07
⏰풀이 시간: 30분
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: BFS

✍ 풀이 방법
방문한 적 없는 섬의 위치부터 h-1, w-1까지 탐색(BFS)하며 어디까지 섬인지 방문 표시한다.
모든 섬의 시작 좌표에서 BFS를 시작하므로 BFS 탐색을 해야 할 때 count를 1씩 증가시킨 뒤 정답으로 제출!
주의 할 점은 상하좌우 뿐 아니라 대각선에 섬이 있을 때도 고려 해야 한다.
