### ISSUE TITLE
[실버2] 11725. 트리의 부모 찾기 

### ISSUE THREAD

**Issue by ramrami-S** [Hanbat-Algo-Study/algorithm#231]
🔗 문제 링크
https://www.acmicpc.net/problem/11725

💡 풀이 사항
📆풀이 일자: 2024.00.00
⏰풀이 시간: 00분 00초
✨채점 결과: 오답🙅‍♀️🙅‍♂️/시간 초과⌛/런타임 에러⏱/정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등

✍ 풀이 방법
(풀이 접근 및 방법에 대한 설명)

**Comment by jisooolee** [comment]
🔗 문제 링크
#232 

💡 풀이 사항
📆풀이 일자: 2024.02.06
⏰풀이 시간: 40분
✨채점 결과: 정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: DFS

✍ 풀이 방법
- DFS로 구현했다.
- DFS 탐색 과정에서 다음에 방문할 노드를 stack에 넣어줄 때, 부모 노드의 번호를 String 배열에 저장해주었다.

**Comment by ensk26** [comment]
🔗 문제 링크
https://github.com/Hanbat-Algo-Study/algorithm/pull/250

💡 풀이 사항
📆풀이 일자: 2024.02.010
⏰풀이 시간: 20분
✨채점 결과: 정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: DFS

✍ 풀이 방법

DFS를 이용해 다음 노드의 부모를 찾아 배열에 따로 저장해두었다.

**Comment by GeonHui2** [comment]
🔗 문제 링크
#247 

💡 풀이 사항
📆풀이 일자: 2024.02.07
⏰풀이 시간: 40분
✨채점 결과: 정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: DFS

✍ 풀이 방법
- 구현으로 풀 수 있을 거 같아서 시도했지만 틀려서 DFS로 다시 풀었다.
- DFS를 통해서 노드의 부모를 배열에 저장 후 StringBuilder로 다시 출력하였다.

**Comment by ramrami-S** [comment]
🔗 문제 링크
#259 

💡 풀이 사항
📆풀이 일자: 2024.02.12
⏰풀이 시간: 19분 12초
✨채점 결과: 정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: DFS

✍ 풀이 방법
인접리스트로 노드와 자식 정보를 저장하고 N-1 사이즈 결과 배열을 만든다.
노드를 순회하면서 자식을 조회 했을 때, 방문하지 않은 자식이라면 결과 배열의 자식 인덱스에 노드(부모)를 기록한다.
마지막에 결과 배열을 출력해주면 끝!

**Comment by skdudddl** [comment]
🔗 문제 링크
#260 

💡 풀이 사항
📆풀이 일자: 2024.02.12
⏰풀이 시간: 약 1시간
✨채점 결과: 정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: DFS

✍ 풀이 방법

- 이번엔 이차원배열이 아닌 graph로 구현해서 시간이 오래걸렸다.
- dfs로 탐색 돌려주었고 parent의 배열을 따로 만들어서 출력했다.
