### ISSUE TITLE
[골드5] 15686. 치킨 배달

### ISSUE THREAD

**Issue by skdudddl** [Hanbat-Algo-Study/algorithm#262]
🔗 문제 링크
https://www.acmicpc.net/problem/15686

🔥 메모리: 
🔥 시간: 

💡 풀이 사항
📆풀이 일자: 2024.00.00
⏰풀이 시간: 00분 00초
✨채점 결과: 오답🙅‍♀️🙅‍♂️/시간 초과⌛/런타임 에러⏱/정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등

✍ 풀이 방법
(풀이 접근 및 방법에 대한 설명)

**Comment by ensk26** [comment]
🔗 문제 링크
https://github.com/Hanbat-Algo-Study/algorithm/pull/281

🔥 메모리: 16180
🔥 시간: 212

💡 풀이 사항
📆풀이 일자: 2024.02.16
⏰풀이 시간: 30분
✨채점 결과: 정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 조합 + 완탐

✍ 풀이 방법
재귀로 치킨 가게 조합을 구한고 치킨 가게와 집 거리를 구했다.

**Comment by GeonHui2** [comment]
🔗 문제 링크
#292 

🔥 메모리: 17172KB
🔥 시간: 268ms

💡 풀이 사항
📆풀이 일자: 2024.02.18
⏰풀이 시간: 30분
✨채점 결과: 정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 구현/조합

✍ 풀이 방법
- 치킨집과 집의 좌표를 각 배열로 저장한다.
- 조합을 통해서 치킨집 경우의 수를 구하고 각 치킨집과 집의 거리의 최소값을 구해서 비교하였다.

**Comment by ramrami-S** [comment]
🔗 문제 링크
#307 


🔥 메모리: 15804kb
🔥 시간: 196ms



💡 풀이 사항
📆풀이 일자: 2024.02.20
⏰풀이 시간: 30분
✨채점 결과: 정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 구현/조합

✍ 풀이 방법
치킨집 문 닫을 곳 닫는 모든 경우에서 치킨 거리를 계산하며 최소값 비교

**Comment by skdudddl** [comment]
🔗 문제 링크
#303

🔥 메모리: 13656
🔥 시간: 160

💡 풀이 사항
📆풀이 일자: 2024.02.19
⏰풀이 시간: 20분
✨채점 결과: 정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 조합 , 구현

✍ 풀이 방법

- 조합으로 치킨집을 m개 뽑았다.
- 집 별로 치킨집의 최소거리를 구하기 때문에 완탐으로 골라둔 치킨집과의 거리를 구하고 도시거리까지 구한다.
- 그 중에 최소값을 비교한다.
