### ISSUE TITLE
[골드4] 17406. 배열돌리기4

### ISSUE THREAD

**Issue by skdudddl** [Hanbat-Algo-Study/algorithm#263]
🔗 문제 링크
https://www.acmicpc.net/problem/17406

💡 풀이 사항
📆풀이 일자: 2024.00.00
⏰풀이 시간: 00분 00초
✨채점 결과: 오답🙅‍♀️🙅‍♂️/시간 초과⌛/런타임 에러⏱/정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등

✍ 풀이 방법
(풀이 접근 및 방법에 대한 설명)

**Comment by ensk26** [comment]
🔗 문제 링크
https://github.com/Hanbat-Algo-Study/algorithm/pull/288

💡 풀이 사항
📆풀이 일자: 2024.02.17
⏰풀이 시간: 120분
✨채점 결과: 정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: DFS/구현

✍ 풀이 방법
순열로 돌리는 순서를 정하고 행의 합의 최소 값을 구했다.

**Comment by jisooolee** [comment]
🔗 문제 링크
#268 

💡 풀이 사항
📆풀이 일자: 2024.02.17
⏰풀이 시간: 120분
✨채점 결과: 정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: DFS/구현

✍ 풀이 방법
순열로 돌리는 순서를 정하고 행의 합의 최소 값을 구했다.

**Comment by GeonHui2** [comment]
🔗 문제 링크
#301 

🔥 메모리: 25288KB
🔥 시간: 216ms

💡 풀이 사항
📆풀이 일자: 2024.02.08
⏰풀이 시간: 1시간
✨채점 결과: 정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 구현

✍ 풀이 방법
- 회전 연산의 조합을 구해주었다.
- 각 조합 별로 회전을 진행하고 배열의 최소값을 변경해주었다.

**Comment by ramrami-S** [comment]
🔗 문제 링크
#306 

💡 풀이 사항
📆풀이 일자: 2024.02.20
⏰풀이 시간: 2시간 이상
✨채점 결과: 틀렸는데 왜 틀렸는지 모르겠어서 쌤한테 여쭤볼 예정 (예시와 게시판의 반례도 다 맞음 ㅠ)
📃예상 문제 유형: 순열, 구현

✍ 풀이 방법
연산의 모든 순서 조합으로 배열을 회전시켜 본다.
각 연산을 마친 후 배열값을 구해주고 최소값을 정답으로 제출

**Comment by skdudddl** [comment]
🔗 문제 링크
#303

🔥 메모리: 34956 KB
🔥 시간: 192 ms

💡 풀이 사항
📆풀이 일자: 2024.02.08
⏰풀이 시간: 2시간
✨채점 결과: 정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 순열, 구현

✍ 풀이 방법

- 연산 순서를 k라는 배열에 넣어주고 그 배열을 순열로 순서를 정해줬다.
- 원래 배열은 수정하면 안되니까 따로 copy해준 배열로 회전했다.
- 그렇게 구한 값들의 min값을 구해준다.
