### ISSUE TITLE
[골드4] 17471. 게리맨더링

### ISSUE THREAD

**Issue by skdudddl** [Hanbat-Algo-Study/algorithm#264]
🔗 문제 링크
https://www.acmicpc.net/problem/17471

🔥 메모리: 
🔥 시간: 

💡 풀이 사항
📆풀이 일자: 2024.00.00
⏰풀이 시간: 00분 00초
✨채점 결과: 오답🙅‍♀️🙅‍♂️/시간 초과⌛/런타임 에러⏱/정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등

✍ 풀이 방법
(풀이 접근 및 방법에 대한 설명)

**Comment by GeonHui2** [comment]
🔗 문제 링크
#299 


🔥 메모리: 13156KB
🔥 시간: 100ms


💡 풀이 사항
📆풀이 일자: 2024.02.17
⏰풀이 시간: 1시간
✨채점 결과: 정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: BFS

✍ 풀이 방법
- 지역을 2개로 나누는 조합을 구해준다.
- 나눈 조합을 BFS를 활용해서 2개의 구역으로 나눌 수 있는 경우인지 확인한다.
- 2개의 구역으로 나누어지면 각 구역의 인구 수 차를 구한다.

**Comment by ensk26** [comment]
🔗 문제 링크
https://github.com/Hanbat-Algo-Study/algorithm/pull/304

🔥 메모리: 
🔥 시간: 

💡 풀이 사항
📆풀이 일자: 2024.02.19
⏰풀이 시간: 2일 이상
✨채점 결과: 오답🙆‍♀️🙆‍♂️
📃예상 문제 유형: BFS

✍ 풀이 방법

- 조합을 구해서, 해당 조합이 잘 나누어져 있는지 확인했다.

**Comment by ramrami-S** [comment]
🔗 문제 링크
#308 


🔥 메모리: 14212kb
🔥 시간: 120ms



💡 풀이 사항
📆풀이 일자: 2024.02.19
⏰풀이 시간: 1시간?
✨채점 결과: 정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 조합, BFS

✍ 풀이 방법
지역구를 나눌 수 있는 모든 경우의 수에서 나눈 두 지역구 각각 연결 그래프인지 확인한 다음, 둘 다 연결 그래프라면 각각 지역구의 인원 수 차를 구한다. 인원수의 차의 최소값이 정답

**Comment by skdudddl** [comment]
🔗 문제 링크
#328 

🔥 메모리: 13580 KB
🔥 시간: 104 ms

💡 풀이 사항
📆풀이 일자: 2024.02.22
⏰풀이 시간: 1시간 이상
✨채점 결과: 정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 서로소

✍ 풀이 방법

- 조합으로 그룹을 나눠준다.
- union할 때 isSelected가 부모와 자식이 같을 때 groupA로 넣어준다.
- 만약 루트가 자신의 부모와 같을 경우만 valid처리 해준다.
- 그 후 인구의 차를 구한다.
