### ISSUE TITLE
[골드5] 14503. 로봇 청소기 

### ISSUE THREAD

**Issue by skdudddl** [Hanbat-Algo-Study/algorithm#266]
🔗 문제 링크
https://www.acmicpc.net/problem/14503

🔥 메모리: 
🔥 시간: 

💡 풀이 사항
📆풀이 일자: 2024.00.00
⏰풀이 시간: 00분 00초
✨채점 결과: 오답🙅‍♀️🙅‍♂️/시간 초과⌛/런타임 에러⏱/정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등

✍ 풀이 방법
(풀이 접근 및 방법에 대한 설명)

**Comment by ramrami-S** [comment]
🔗 문제 링크
코드는 집에 가서 올리겠음 ><

🔥 메모리: 11868kb
🔥 시간: 84ms

💡 풀이 사항
📆풀이 일자: 2024.02.16
⏰풀이 시간: 2시간 초과
✨채점 결과: 정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: DFS

✍ 풀이 방법
로봇을 문제에 나온 조건에 맞게 움직이면서 청소를 할 때마다 정답을 1씩 늘려준다.
몇 가지 고려 해야 될 것들이 있어서 정답이 틀리게 나와서 시간이 오래 걸렸다.

1. 청소가 된 곳을 1로 표시했었는데 벽도 1이라 헷갈림 -> 청소 된 곳은 2로 표시, 1은 벽!
2. 입력된 방에서 가장 자리는 모두 벽이다.
3. 청소 안된 빈칸이 있으면 바로 회전해야 된다. 4방향 모두 탐색할 필요 없음

**Comment by GeonHui2** [comment]
🔗 문제 링크
#296 

🔥 메모리: 11864kb
🔥 시간: 84ms

💡 풀이 사항
📆풀이 일자: 2024.02.15
⏰풀이 시간: 1시간 30분
✨채점 결과: 정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 백트래킹

✍ 풀이 방법
- 청소 되지 않은 빈 칸이 있으면 로봇은 해당 방향으로 직진하고 청소한다.
- 만약 직진한 방향이 벽이라면 로봇은 해당 방향으로 회전하고 회전한 후에도 청소 가능한 공간이 없다면 로봇은 다시 회전한다.
- 만약 로봇이 네 방향 모두 청소 가능한 공간이 없다면 후진을 시도하고 후진을 해도 벽이라면 작업을 중지하고 종료합니다.

**Comment by jisooolee** [comment]
🔗 문제 링크
#269  

🔥 메모리: 14472 KB
🔥 시간: 128 ms

💡 풀이 사항
📆풀이 일자: 2024.02.13
⏰풀이 시간: 1시간 30분
✨채점 결과: 정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: dfs

✍ 풀이 방법
- dfs로 청소기가 움직일 수 없을 때까지 탐색을 진행했다.

**Comment by skdudddl** [comment]
🔗 문제 링크
#303 

🔥 메모리: 11852kb
🔥 시간: 88ms

💡 풀이 사항
📆풀이 일자: 2024.02.19
⏰풀이 시간: 1시간
✨채점 결과: 정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: DFS

✍ 풀이 방법

- 청소되지 않은 빈칸이 없을 때까지 진행하기 때문에 DFS로 구현했다.
- 작동방식에 나온 대로, isPossible이라는 변수를 설정하여 빈칸 유무를 체크했다.
- 그러고 있는 경우와 없는 경우 방향을 바꿔 dfs하도록 구현했다.
