### ISSUE TITLE
[SWEA] 4012 . 요리사

### ISSUE THREAD

**Issue by skdudddl** [Hanbat-Algo-Study/algorithm#270]
🔗 문제 링크
https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AWIeUtVakTMDFAVH

🔥 메모리: 
🔥 시간: 

💡 풀이 사항
📆풀이 일자: 2024.00.00
⏰풀이 시간: 00분 00초
✨채점 결과: 오답🙅‍♀️🙅‍♂️/시간 초과⌛/런타임 에러⏱/정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등

✍ 풀이 방법
(풀이 접근 및 방법에 대한 설명)

**Comment by ramrami-S** [comment]
🔗 문제 링크
코드 집가서 올리겠음 22


🔥 메모리: 
🔥 시간: 



💡 풀이 사항
📆풀이 일자: 2024.02.16
⏰풀이 시간: 8분
✨채점 결과: 정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 조합

✍ 풀이 방법
N개의 식재료 중 N/2개씩 2개를 선택하고, 각각 선택된 재료들로 만들 수 있는 요리를 다 만들어 본다. 모든 요리의 맛 중 가장 적은 맛을 정답으로 업데이트 하면 됨

**Comment by ensk26** [comment]
🔗 문제 링크
https://github.com/Hanbat-Algo-Study/algorithm/pull/293

🔥 메모리: 23,560 kb
🔥 시간: 250 ms 

💡 풀이 사항
📆풀이 일자: 2024.02.18
⏰풀이 시간: .30분
✨채점 결과: 정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 조합

✍ 풀이 방법
- n개의 식재료에서 2/n개를 선택하는 조합을 만들어서 맛 시너지 차를 구했다.

**Comment by GeonHui2** [comment]
🔗 문제 링크
#295


🔥 메모리: 22,276kb
🔥 시간: 317ms



💡 풀이 사항
📆풀이 일자: 2024.02.18
⏰풀이 시간: 30분
✨채점 결과: 정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 조합

✍ 풀이 방법
- n개의 식재료를 2개로 나누고 각 재료들을 활용해서 시너지의 합을 구한다.
- 2개의 요리 시너지 합의 차가 가장 작은 경우를 찾아서 출력했다.

**Comment by jisooolee** [comment]
🔗 문제 링크
#287


🔥 메모리: 24104 kb
🔥 시간: 158ms



💡 풀이 사항
📆풀이 일자: 2024.02.02
⏰풀이 시간: 기억 안 남
✨채점 결과: 정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 조합

✍ 풀이 방법
- 조합으로 식재료를 선택해주고, 각 조합마다 선택된 식재료와 선택되지 않은 식재료의 시너지를 각각 구해주었다.

**Comment by skdudddl** [comment]
🔗 문제 링크
#271 

🔥 메모리: 22,112 kb
🔥 시간: 321 ms

💡 풀이 사항
📆풀이 일자: 2024.02.15
⏰풀이 시간: .30분
✨채점 결과: 정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 조합

✍ 풀이 방법

- n개의 식재료에서 n/2개로 조합 만들어줬다.
-  isSelected = true는 a, isSelected= fasle인 건 b로 시너지 차를 구했다.
