### ISSUE TITLE
[D3] 1220. Magnetic

### ISSUE THREAD

**Issue by jisooolee** [Hanbat-Algo-Study/algorithm#29]
### 🔗 문제 링크
https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AV14hwZqABsCFAYD

### 💡 풀이 사항
📆풀이 일자: 2024.00.00
⏰풀이 시간: 00분 00초
✨채점 결과: 오답🙅‍♀️🙅‍♂️/시간 초과⌛/런타임 에러⏱/정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등

### ✍ 풀이 방법
(풀이 접근 및 방법에 대한 설명)

**Comment by jisooolee** [comment]
### 문제 링크
#28 

### 풀이 사항
풀이 일자: 2024.01.18
풀이 시간: 50분 00초
채점 결과: 정답
예상 문제 유형: 완전탐색

### 풀이 방법
- 이차원 배열 board에 테이블 위 자성체들의 위치 값을 넣어준다.
- board의 첫 번째 열부터 백 번째 열까지 각 열에 대한 탐색을 진행한다.
- 열 탐색을 시작하기 전, 방향을 나타내는 dir 변수를 0으로 초기화한다.
- 탐색을 진행하면서 붉은 자성체를 발견할 경우 dir 값을 1로 변경해준다.
- 푸른 자성체를 발견한 경우, dir 값이 1인 경우에 교착 상태 개수를 1 증가해준 뒤에 dir을 다시 초기값인 0으로 변경해준다.

**Comment by ramrami-B** [comment]
### 🔗 문제 링크
https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AV14hwZqABsCFAYD

### 💡 풀이 사항
📆풀이 일자: 2024.01.18
⏰풀이 시간: 51분 23초
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: 구현

### ✍ 풀이 방법
S극이 아래에 있기 때문에 N극인 좌표들은 아래로 내려가려는 성향이 있다.
하지만 아래 방향에 S극이 있으면 교착상태가 되기 때문에 N극인 좌표인데 아래 방향에 S극이 있는 좌표의 갯수를 구하면 된다.

1. 2차원 배열 전체 탐색을 하다가 N극을 만나면, 아래 방향으로 탐색한다.
2-1. N극 좌표의 아래 방향에 S극이 있으면 answer++를 해주고, 탐색을 멈춘다
2-2. 만약  같은 N극을 만나면 그냥 탐색을 멈춘다

**Comment by GeonHui2** [comment]
### 🔗 문제 링크
#59 

### 💡 풀이 사항
📆풀이 일자: 2024.01.18
⏰풀이 시간: 12분00초
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: 구현

### ✍ 풀이 방법
- 2차원 배열을 세로로 탐색을 하면서 N극을 만나게 되면 check를 true로 바꿔준다.
- check가 true면서 S극을 만나게 되면 result++을 해주고 check를 fasle로 바꿔준다.

**Comment by ensk26** [comment]
https://github.com/Hanbat-Algo-Study/algorithm/pull/89

### 풀이 사항
풀이 일자: 2024.01.21
풀이 시간: 1시 30분
채점 결과: 정답
예상 문제 유형: 구현

### 풀이 방법

- n극이 위에 있어, n극과 s극이 서로 쌍을 이루면 위아래로 교착상태가 일어난다.
- 그래서 이전값은 n극 이면서 현재 값은 s극인 경우를 찾았다.
- 찾고 난 뒤 초기화를 안해줘 푸는데 오래 걸렸다.
