### ISSUE TITLE
[골드 3] 16637. 괄호 추가하기

### ISSUE THREAD

**Issue by skdudddl** [Hanbat-Algo-Study/algorithm#309]
🔗 문제 링크
https://www.acmicpc.net/problem/16637

🔥 메모리: 
🔥 시간: 

💡 풀이 사항
📆풀이 일자: 2024.00.00
⏰풀이 시간: 00분 00초
✨채점 결과: 오답🙅‍♀️🙅‍♂️/시간 초과⌛/런타임 에러⏱/정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등

✍ 풀이 방법
(풀이 접근 및 방법에 대한 설명)

**Comment by GeonHui2** [comment]
🔗 문제 링크
#339 

🔥 메모리: 11568 KB
🔥 시간: 76 ms

💡 풀이 사항
📆풀이 일자: 2024.02.23
⏰풀이 시간: 1시간 30분
✨채점 결과: 정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: DFS

✍ 풀이 방법
- 1시간 정도 고민했는데 코드로 구현을 어떻게 해야하는지 잘 몰라서 다른 사람들의 코드를 참고했습다.
- DFS를 통해서 괄호를 안 만드는 경우와 괄호를 만드는 경우를 각각 DFS를 통해서 계산했습니다.
- 계산 후 최댓값을 갱신했습니다.

**Comment by ramrami-S** [comment]
🔗 문제 링크
#352 


🔥 메모리: 11712 
🔥 시간: 80


💡 풀이 사항
📆풀이 일자: 2024.02.26
⏰풀이 시간: 2시간
✨채점 결과: 정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 재귀

✍ 풀이 방법
(풀이 접근 및 방법에 대한 설명)

**Comment by skdudddl** [comment]
🔗 문제 링크
#354 

🔥 메모리: 11548 KB
🔥 시간: 80 ms

💡 풀이 사항
📆풀이 일자: 2024.02.26
⏰풀이 시간: 2시간 이상
✨채점 결과: 정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: DFS

✍ 풀이 방법

- 너무 모르겠어서 gpt선생님과 함께,,,
- operation, number따로 받아준다. 
- dfs를 돌릴 때 괄호 추가하는 것과 안 하는 것 나눠서 부분집합처럼  구한다. 
- 계속 틀렸다고 나와서 왜그런지 봤는데 integer.minvalue값으로 처리 안 해줘서 난 거였다.
- 다시 풀어봐야할 것 같다
