### ISSUE TITLE
[골드3] 17135. 캐슬 디펜스

### ISSUE THREAD

**Issue by skdudddl** [Hanbat-Algo-Study/algorithm#310]
🔗 문제 링크
https://www.acmicpc.net/problem/17135

🔥 메모리: 
🔥 시간: 

💡 풀이 사항
📆풀이 일자: 2024.00.00
⏰풀이 시간: 00분 00초
✨채점 결과: 오답🙅‍♀️🙅‍♂️/시간 초과⌛/런타임 에러⏱/정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등

✍ 풀이 방법
(풀이 접근 및 방법에 대한 설명)

**Comment by jisooolee** [comment]
🔗 문제 링크
#346 


🔥 메모리: 16536 KB
🔥 시간: 212 ms

💡 풀이 사항
📆풀이 일자: 2024.02.25
⏰풀이 시간: 2시간 이상
✨채점 결과: 정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 구현

✍ 풀이 방법
- 조합으로 궁수의 위치를 정함
- 적의 위치 정보를 가진 배열을 생성하고, 게임이 시작될 때마다 배열을 복사한 다음 적의 위치 정보를 갱신

**Comment by skdudddl** [comment]
🔗 문제 링크
#350 

🔥 메모리: 16852 KB
🔥 시간: 244 ms

💡 풀이 사항
📆풀이 일자: 2024.02.22
⏰풀이 시간: 3시간 이상
✨채점 결과: 정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 구현

✍ 풀이 방법

- 궁수의 위치를 조합으로 선택한다.
- 궁수 공격하고 적 카운트를 해준다.
- 그리고 적이 이동한다. 
- 계속 map을 복사해주면서 진행한다.
- 계속 안 풀려서 지피티의 도움을 스알짝 받았습니다요.ㅜㅜ

**Comment by GeonHui2** [comment]
🔗 문제 링크
#355 

🔥 메모리: 12476KB
🔥 시간: 88ms

💡 풀이 사항
📆풀이 일자: 2024.02.26
⏰풀이 시간: 2시간 이상
✨채점 결과: 정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 구현

✍ 풀이 방법
- 조합을 통해서 궁수의 위치를 구한다.
- 궁수의 위치를 올리면서 적을 공격했다.
- 공격하는 부분을 몰라서 정답을 참고했다.

**Comment by ramrami-S** [comment]
🔗 문제 링크
#356 


🔥 메모리: 41832
🔥 시간: 388

💡 풀이 사항
📆풀이 일자: 2024.02.26
⏰풀이 시간: 2시간 이상
✨채점 결과: 정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 조합, 우선순위 큐

✍ 풀이 방법
(풀이 접근 및 방법에 대한 설명)
