### ISSUE TITLE
[골드4] 17281. ⚾

### ISSUE THREAD

**Issue by skdudddl** [Hanbat-Algo-Study/algorithm#311]
🔗 문제 링크
https://www.acmicpc.net/problem/17281

🔥 메모리: 
🔥 시간: 

💡 풀이 사항
📆풀이 일자: 2024.00.00
⏰풀이 시간: 00분 00초
✨채점 결과: 오답🙅‍♀️🙅‍♂️/시간 초과⌛/런타임 에러⏱/정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등

✍ 풀이 방법
(풀이 접근 및 방법에 대한 설명)

**Comment by GeonHui2** [comment]
문제 링크
#331

메모리: 61484KB
시간: 472ms

풀이 사항
풀이 일자: 2024.02.22
⏰풀이 시간: 1시간
✨채점 결과: 정답♀♂
예상 문제 유형: 구현, 순열

✍ 풀이 방법
- 타자들의 순서를 순열을 통해서 나타낸다.
- 타자의 순서의 맞게 이닝을 진행하면서 구현을 통해 야구 게임을 진행 후 나오는 점수의 최댓값을 구해주었다.

**Comment by skdudddl** [comment]
문제 링크
#344 

메모리: 63596 KB
시간: 580 ms

풀이 사항
풀이 일자: 2024.02.24
⏰풀이 시간: 1시간
✨채점 결과: 정답♀♂
예상 문제 유형: 순열, 구현

✍ 풀이 방법

- 타자들의 순서를 순열로 설정한다.
- 규칙에 맞게 구현해준다. 
- 타자의 번호가 9보다 커질 때 idx = 0으로 설정해줬다.
-

**Comment by jisooolee** [comment]
문제 링크
#349 

메모리: 59720 KB
시간: 492 ms

풀이 사항
풀이 일자: 2024.02.25
⏰풀이 시간: 2시간 이상
✨채점 결과: 정답♀♂
예상 문제 유형: 순열, 구현

✍ 풀이 방법
- 타자들의 순서를 순열로 설정한다.
- 나머지는 그냥 구현
- 처음에 for문을 이용해 각 루수 별 주자의 존재 여부를 검사하고, 규칙에 맞게 점수를 증가해주었는데 틀렸다
- 2시간 넘게 고민해봤지만 아무리 생각해봐도 틀린 이유를 모르겠다
- 그래서 그냥 하드 코딩으로 점수 증가 규칙을 구현해주었다(Thanks to 건희)
- 야구 진짜 별로다

**Comment by ramrami-S** [comment]
🔗 문제 링크
#358 


🔥 메모리: 64352
🔥 시간: 548


💡 풀이 사항
📆풀이 일자: 2024.02.26
⏰풀이 시간: 2시간 이상
✨채점 결과: 정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 순열, 구현

✍ 풀이 방법
감독이 좋아하는 1번 선수?는 항상 4번이 가도록 하면서 모든 경우의 타순을 고려한다.
타순이 정해지면 게임을 진행하는데, 각 베이스를 boolean 배열로 표현해서 선수가 있으면 true, 없으면 false로 지정해 준다.
안타인지 홈런인지 등에 따라 처리해 주면서 해당 타순으로 낼 수 있는 점수를 계산한 다음, 가장 많이 득점하는 점수를 정답으로 한다
