### ISSUE TITLE
[골드5] 21610. 마법사 상어와 비바라기

### ISSUE THREAD

**Issue by skdudddl** [Hanbat-Algo-Study/algorithm#312]
🔗 문제 링크
https://www.acmicpc.net/problem/21610

🔥 메모리: 
🔥 시간: 

💡 풀이 사항
📆풀이 일자: 2024.00.00
⏰풀이 시간: 00분 00초
✨채점 결과: 오답🙅‍♀️🙅‍♂️/시간 초과⌛/런타임 에러⏱/정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등

✍ 풀이 방법
(풀이 접근 및 방법에 대한 설명)

**Comment by GeonHui2** [comment]
문제 링크
#347 

메모리: 25908 KB
시간: 216 ms

풀이 사항
풀이 일자: 2024.02.24
⏰풀이 시간: 1시간
✨채점 결과: 정답🙅‍♀️🙅‍♂️
예상 문제 유형: 구현

✍ 풀이 방법
- 이동 후 새로운 구름을 생성하는 로직을 구현했습니다.
- 최종 이동 후 바구니에 들어있는 물의 양의 합을 구했습니다.

**Comment by skdudddl** [comment]
문제 링크
#342 

메모리: 12456 KB
시간: 144 ms

풀이 사항
풀이 일자: 2024.02.24
⏰풀이 시간: 1시간
✨채점 결과: 정답
예상 문제 유형: 구현

✍ 풀이 방법

-  구름이동 하는 cloudcheck 함수 구현했다.
- 그 후 대각선 방향에 물 확인하는 watercheck함수 구현했다.
- 그 후 2이상이고 구름이 아닌 곳에서 구름으로 확인하는 removewater함수를 구현했다.

**Comment by jisooolee** [comment]
🔗 문제 링크
#351 


🔥 메모리: 19084 KB
🔥 시간: 436 ms


💡 풀이 사항
📆풀이 일자: 2024.02.26
⏰풀이 시간: 2시간?
✨채점 결과: 정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 구현

✍ 풀이 방법
- 구름 좌표 관리하는 clouds 리스트 이용
- 초기 구름 좌표 clouds에 넣어줌
- 각 이동 별로 move method 실행
- move method에서 먼저 구름의 이동 좌표 구해주고, 해당 좌표 값 1 증가
- 구름 좌표 조회하면서 bug method 실행
- 이동이 끝나면 물 양 확인해서 구름 만들어주는 method 실행하고, 구름 좌표 갱신

**Comment by ensk26** [comment]
문제 링크
https://github.com/Hanbat-Algo-Study/algorithm/pull/353

메모리: 24536 KB
시간: 256 ms

풀이 사항
풀이 일자: 2024.02.26
⏰풀이 시간: 3시간
✨채점 결과: 정답🙆‍♀️🙆‍♂️
예상 문제 유형: 구현

✍ 풀이 방법

이동하고 비내리고, 물 복사하는 과정을 만들었다.

**Comment by ramrami-S** [comment]
🔗 문제 링크
#359 


🔥 메모리: 
🔥 시간: 


💡 풀이 사항
📆풀이 일자: 2024.02.26
⏰풀이 시간: 2시간 이상
✨채점 결과: 오답🙅‍♀️🙅‍♂️
📃예상 문제 유형: 구현

✍ 풀이 방법
문제에 나온대로 풀었다 ㅠ.ㅠ
