### ISSUE TITLE
[SWEA] 5650. 핀볼 게임

### ISSUE THREAD

**Issue by skdudddl** [Hanbat-Algo-Study/algorithm#313]
🔗 문제 링크
https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AWXRF8s6ezEDFAUo

🔥 메모리: 
🔥 시간: 

💡 풀이 사항
📆풀이 일자: 2024.00.00
⏰풀이 시간: 00분 00초
✨채점 결과: 오답🙅‍♀️🙅‍♂️/시간 초과⌛/런타임 에러⏱/정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등

✍ 풀이 방법
(풀이 접근 및 방법에 대한 설명)

**Comment by ramrami-S** [comment]
🔗 문제 링크
#337 


🔥 메모리: 42,012 kb
🔥 시간: 1,709 ms


💡 풀이 사항
📆풀이 일자: 2024.02.24
⏰풀이 시간: 1시간 30분?
✨채점 결과: 정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 시뮬

✍ 풀이 방법
(풀이 접근 및 방법에 대한 설명)

**Comment by skdudddl** [comment]
🔗 문제 링크
#357 
🔥 메모리: 48,432kb
🔥 시간:  183ms

💡 풀이 사항
📆풀이 일자: 2024.02.26
⏰풀이 시간: 2시간 이상
✨채점 결과: 실패(런타임 에러) ps. 왜나는데;;;
📃예상 문제 유형: 시뮬레이션

✍ 풀이 방법

-  0일 때 각 방향마다 시뮬레이션을 돌려줬다.
-  기저조건을 정해주고 1-5일 때 방향을 바꿔주는 함수를 구현했다.
- 6-10일 때 다른 웜홀을 찾는 함수를 구현했다.
