### ISSUE TITLE
[SWEA] 2382. 미생물 격리

### ISSUE THREAD

**Issue by skdudddl** [Hanbat-Algo-Study/algorithm#314]
🔗 문제 링크
https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AV597vbqAH0DFAVl

🔥 메모리: 
🔥 시간: 

💡 풀이 사항
📆풀이 일자: 2024.00.00
⏰풀이 시간: 00분 00초
✨채점 결과: 오답🙅‍♀️🙅‍♂️/시간 초과⌛/런타임 에러⏱/정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등

✍ 풀이 방법
(풀이 접근 및 방법에 대한 설명)

**Comment by jisooolee** [comment]
🔗 문제 링크
#321 


🔥 메모리: 98,656 KB
🔥 시간: 854 ms


💡 풀이 사항
📆풀이 일자: 2024.02.20
⏰풀이 시간: 1시간 반?
✨채점 결과: 정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 구현

✍ 풀이 방법
- 군집을 방향 별로 이동시켜주었다.
- 군집의 이동 후 위치를 key로 갖고, 군집 list의 index를 value로 갖는 HashMap을 생성해주었다.
- 군집을 전부 이동시키고, Map을 돌면서 한 위치에 여러 개의 군집이 위치할 경우, 개체 수가 가장 큰 군집의 index를 구해주었다.
- 개체 수가 가장 큰 군집에 위치가 중복된 군집의 개체 수를 전부 더한 값을 넣어주고, 나머지 중복된 군집의 개체 수 값은 0으로 바꿔준다.

**Comment by ramrami-S** [comment]
🔗 문제 링크
#329 


🔥 메모리: 
🔥 시간: 


💡 풀이 사항
📆풀이 일자: 2024.00.00
⏰풀이 시간: 00분 00초
✨채점 결과: 오답🙅‍♀️🙅‍♂️/시간 초과⌛/런타임 에러⏱/정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등

✍ 풀이 방법
(풀이 접근 및 방법에 대한 설명)

**Comment by skdudddl** [comment]
🔗 문제 링크
#350

🔥 메모리: 55,096 kb
🔥 시간: 307 ms

💡 풀이 사항
📆풀이 일자: 2024.2.20
⏰풀이 시간: 3시간 이상
✨채점 결과: 정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 구현(시뮬)

✍ 풀이 방법

- 이거 진짜 너무 안 풀려서 강사님 코드를 스알짝 봤습네다 ㅜㅜ
- 미생물의 정보를 virus클래스를 만들어서 저장해줫다.
- comparable을 사용해서 순위에 따라 정렬을 해줬다.
- virus를 저장하는 리스트를 만들어줬다.
- 빨간 지역과 아닌 지역에 따른 시뮬레이션을 따로 구현해주고 답을 구했다.

**Comment by ensk26** [comment]
🔗 문제 링크
https://github.com/Hanbat-Algo-Study/algorithm/pull/353



💡 풀이 사항
📆풀이 일자: 2024.2.20
⏰풀이 시간: 일주일
✨채점 결과:  실패
📃예상 문제 유형: 구현(시뮬)

✍ 풀이 방법

런타임 에러난다.
