### ISSUE TITLE
[골드1] 17472. 다리 만들기 2(3/5)

### ISSUE THREAD

**Issue by skdudddl** [Hanbat-Algo-Study/algorithm#318]
🔗 문제 링크
https://www.acmicpc.net/problem/17472

🔥 메모리: 
🔥 시간: 

💡 풀이 사항
📆풀이 일자: 2024.00.00
⏰풀이 시간: 00분 00초
✨채점 결과: 오답🙅‍♀️🙅‍♂️/시간 초과⌛/런타임 에러⏱/정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등

✍ 풀이 방법
(풀이 접근 및 방법에 대한 설명)

**Comment by ramrami-S** [comment]
🔗 문제 링크
#334 


🔥 메모리: 
🔥 시간: 


💡 풀이 사항
📆풀이 일자: 2024.00.00
⏰풀이 시간: 00분 00초
✨채점 결과: 오답🙅‍♀️🙅‍♂️/시간 초과⌛/런타임 에러⏱/정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등

✍ 풀이 방법
(풀이 접근 및 방법에 대한 설명)

**Comment by jisooolee** [comment]
🔗 문제 링크
#335


🔥 메모리: 11624 KB
🔥 시간: 76 ms


💡 풀이 사항
📆풀이 일자: 2024.02.23
⏰풀이 시간: 몰라
✨채점 결과: 정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: BFS + MST

✍ 풀이 방법
- bfs를 이용해 각 섬마다 번호 붙이기
- 사방 탐색을 이용해 각 섬을 연결할 수 있는 다리 길이 최소값 구해주기
- 프림 알고리즘을 이용해 답 구해주기

**Comment by skdudddl** [comment]
문제 링크
#340 

🔥 메모리: 11760 KB
🔥 시간: 80 ms

💡 풀이 사항
📆풀이 일자: 2024.02.24
⏰풀이 시간: 모름
✨채점 결과: 정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: BFS + MST(크루스칼) + 서로소

✍ 풀이 방법

- bfs를 이용해서 섬 숫자 설정
- 크루스칼을 이용해서 weight의 최소값 구함
- 모두 연결되었는지 확인을 위해 서로소 이용
