### ISSUE TITLE
[골드4] 15683. 감시(자율)

### ISSUE THREAD

**Issue by skdudddl** [Hanbat-Algo-Study/algorithm#325]
🔗 문제 링크
https://www.acmicpc.net/problem/15683

🔥 메모리: 
🔥 시간: 

💡 풀이 사항
📆풀이 일자: 2024.00.00
⏰풀이 시간: 00분 00초
✨채점 결과: 오답🙅‍♀️🙅‍♂️/시간 초과⌛/런타임 에러⏱/정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등

✍ 풀이 방법
(풀이 접근 및 방법에 대한 설명)

**Comment by jisooolee** [comment]
🔗 문제 링크
#326 


🔥 메모리: 54916 KB
🔥 시간: 376 ms


💡 풀이 사항
📆풀이 일자: 2024.02.21
⏰풀이 시간: 기억 안 남
✨채점 결과: 정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 구현

✍ 풀이 방법
- cctv 위치를 ArrayList에 저장
- cctv를 회전할 경우 감시할 수 있는 구역이 달라지는 모든 방향에 대해, 각 cctv를 회전시킴
- cctv 번호 별로 감시가 가능한 위치의 값을 -1로 변경
- 모든 cctv의 회전 여부가 결정되면 사각지대의 개수를 구해줌

**Comment by skdudddl** [comment]
🔗 문제 링크
#362 

🔥 메모리: 24780 KB
🔥 시간: 156 ms

💡 풀이 사항
📆풀이 일자: 2024.02.28
⏰풀이 시간: 기억 안 남
✨채점 결과: 정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 구현, 조합, bfs

✍ 풀이 방법

- cctv방향 설정과 회전방향을 배열에 넣음
- cctv위치와 type을 클래스 만들고 정보를 arraylist 에 저장
- 재귀할 때 그 전 배열을 copy하고 감시가능한 지역을 -1로 지정
- 0인 개수 구함
