### ISSUE TITLE
[D3] 2805. 농작물 수확하기

### ISSUE THREAD

**Issue by ramrami-B** [Hanbat-Algo-Study/algorithm#34]
### 🔗 문제 링크
https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AV7GLXqKAWYDFAXB

### 💡 풀이 사항
📆풀이 일자: 2024.00.00
⏰풀이 시간: 00분 00초
✨채점 결과: 오답🙅‍♀️🙅‍♂️/시간 초과⌛/런타임 에러⏱/정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등

### ✍ 풀이 방법
(풀이 접근 및 방법에 대한 설명)

**Comment by ramrami-B** [comment]
### #️⃣ 이슈 번호
#54 

### 💡 풀이 사항
📆풀이 일자: 2024.01.20
⏰풀이 시간: 1시간 36분 49초
✨채점 결과: 23/50개 정답🙆‍♀️
📃예상 문제 유형: 구현

### ✍ 풀이 방법

굉장히 킹 받는 문제다.
처음 문제를 읽었을 때, N*N 농장에서 중심점을 찾아서 중심점을 시작으로 + 모양(상하좌우)을 그리며 이익을 추가 해야겠다고 생각했다.
그러다가 왜인지 모르겠지만 갑자기 BFS로 풀어야 할 것 같아서 BFS까지 구현 했는데 결국은 그럴것까지 없다는 것을 깨닫고..
맵에서 규칙을 찾아서 이익을 더해가는 방식으로 풀이했다. (피곤해서 아무렇게나 풀려다가 일이 이렇게 되어 버렸는데 그래서 시간이 더 걸려버리는 어리석은 일을 했다 ㅠㅠ)
농장을 위 부분(0~N/2행)과 아래 부분(~N-1행)으로 나누어서 농장물을 수확할 수 있는 부분의 수익을 전체 수익에 + 해나간다.

킹 받는 문제라고 한 이유는 50개 중 23개(input.txt로 주어지는 테케)만 맞췄기 때문... 로직은 맞는 것 같은데 조금 더 고민이 필요한 것 같다 ㅠ.ㅠ

**Comment by GeonHui2** [comment]
### 🔗 문제 링크
#62 

### 💡 풀이 사항
📆풀이 일자: 2024.01.19
⏰풀이 시간: 18분00초
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: 구현

### ✍ 풀이 방법
- 수확을 하지 않는 영역의 규칙을 먼저 구현했다.
- 반복문을 통해서 Math.abs(N / 2 - i)가 양 옆의 수확하지 않는 영역의 갯수를 의미해서 이를 이용해서 구현했다.

**Comment by jisooolee** [comment]
### #️⃣ 이슈 번호
#53 

### 💡 풀이 사항
📆풀이 일자: 2024.01.21
⏰풀이 시간: 1시간 44분
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: 구현

### ✍ 풀이 방법
- 사실 집중이 안 돼서 멍때리느라 풀이 시간이 조금 오래 걸렸다...
- 각 행을 순회하면서 수익을 더해주었다.
- 먼저 행의 가장 가운데 요소의 수익을 더해주고, 가운데 index를 기준으로 두 번의 반복문을 순회하면서 첫 번째 반복문에서는 index를 감소해가며 수익을 더해주고, 두 번째 반복문에서는 index를 증가해가며 수익을 더해주었다.
- 반복문을 시작하기 전, num이라는 변수를 선언해 각 행마다 더해져야하는 요소의 개수를 조정해주었다.

**Comment by ensk26** [comment]
https://github.com/Hanbat-Algo-Study/algorithm/pull/73

### 풀이 사항
풀이 일자: 2024.01.21
풀이 시간: 18분
채점 결과: 정답
예상 문제 유형: 구현

### 풀이 방법
- 위와 아래를 나눠 만들었다.
- k를 이용해 위는 k=3 ~ 1, 아래는 k=0~3 으로 좌표값을 조절해 구현했다.

**Comment by skdudddl** [comment]
#36

풀이 사항
풀이 일자: 2024.01.20
풀이 시간: 30분
채점 결과: 정답
예상 문제 유형: 구현

풀이 방법

- range가 N/2 - i임을 이용했다
- 전체에서 range에 해당되지 않은 범위를 더하는 식으로 구현했다.
