### ISSUE TITLE
[D3] 1289. 원재의 메모리 복구하기

### ISSUE THREAD

**Issue by GeonHui2** [Hanbat-Algo-Study/algorithm#40]
### 🔗 문제 링크
https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AV19AcoKI9sCFAZN

### 💡 풀이 사항
📆풀이 일자: 2024.00.00
⏰풀이 시간: 00분 00초
✨채점 결과: 오답🙅‍♀️🙅‍♂️/시간 초과⌛/런타임 에러⏱/정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등

### ✍ 풀이 방법
(풀이 접근 및 방법에 대한 설명)

**Comment by GeonHui2** [comment]
### 🔗 문제 링크
#60 

### 💡 풀이 사항
📆풀이 일자: 2024.01.18
⏰풀이 시간: 10분00초
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: 구현

### ✍ 풀이 방법
- 초기화 상태에서는 모드 bit가 0이기 때문에 처음에 확인해야 할 bit를 0으로 하고 비교했다.
- 이전 값과 다른 값으로 변경되면 끝까지 변경되기 때문에 다른 값이면 result++을 하고 확인해야 하는 bit를 해당 값으로 변경해줬다.
- 메모리를 모두 비교하면서 값이 변경되는 부분이 몇 개인지 확인하는 문제였다.

**Comment by ramrami-B** [comment]
### 🔗 문제 링크
#54 (2문제 중첩 되어 있음😅)

### 💡 풀이 사항
📆풀이 일자: 2024.01.22
⏰풀이 시간: 13분 50초
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: 구현

### ✍ 풀이 방법
(풀이 접근 및 방법에 대한 설명)

**Comment by jisooolee** [comment]
### 🔗 문제 링크
#31 

### 💡 풀이 사항
📆풀이 일자: 2024.01.18
⏰풀이 시간: 14분00초
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: 구현

### ✍ 풀이 방법
- 특정 회차에서 특정 index 다음의 bit가 모두 동일하기 때문에 현재 index가 나타내는 bit의 값을 current 변수에 저장해주고, bit 값이 바뀔 때마다 update해준다.
- 만약 현재 index의 bit 값이 current와 다르다면 변경 횟수를 1 증가해주고 current 값을 해당 bit와 동일하게 변경해준다.

**Comment by ensk26** [comment]
https://github.com/Hanbat-Algo-Study/algorithm/pull/73

### 풀이 사항
풀이 일자: 2024.01.21
풀이 시간: 10분
채점 결과: 정답
예상 문제 유형: 구현

### 풀이 방법
- 앞에서부터 변경하면 최소로 변경하는 방법이므로, 순회를 하면서 1인 경우, 0으로 변경 후 나머지 뒤에도 값을 반대로 변경했다.

**Comment by skdudddl** [comment]
🔗 문제 링크
#57

💡 풀이 사항
📆풀이 일자: 2024.01.21
⏰풀이 시간: 20분
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: 구현

✍ 풀이 방법

- 1이 나오고 0이 나오는 것과 0이 나오고 1로 변환할 때 더하는 방식을 생각했다.
- flag라는 변수를 만들고 false로 초기화를 한다.
- flag가 false이고 1일 때 flag를 true로 해주고 cnt +1 처리한다.
- flag가 true이고 0일 때 flagr를 false로 해주고 cnt +1처리한다.
- 이 방식일 때 1은 앞에 0 이나왔어야하고 0은 앞에 1이 나왔어야함을 이용했다.
