### ISSUE TITLE
[D3] 1493. 수의 새로운 연산

### ISSUE THREAD

**Issue by GeonHui2** [Hanbat-Algo-Study/algorithm#41]
### 🔗 문제 링크
https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AV2b-QGqADMBBASw

### 💡 풀이 사항
📆풀이 일자: 2024.00.00
⏰풀이 시간: 00분 00초
✨채점 결과: 오답🙅‍♀️🙅‍♂️/시간 초과⌛/런타임 에러⏱/정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등

### ✍ 풀이 방법
(풀이 접근 및 방법에 대한 설명)

**Comment by GeonHui2** [comment]
### 🔗 문제 링크
#61 

### 💡 풀이 사항
📆풀이 일자: 2024.01.20
⏰풀이 시간: 1시간 30분
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: 구현

### ✍ 풀이 방법
- x좌표와 y좌표를 기준으로 각각 1이 증가할수록 규칙++이 되면서 계속 증가하였다.
- 이 규칙을 찾았지만 문제를 잘 이해하지 못하고 다른 방법으로 구현하는 방법을 찾는 과정에서 시간을 많이 소요되었다.
- 값을 저장하는 2차원 배열의 크기를 얼마나 설정해야 할지 몰라서 찾아보면서 최대 크기의 2배로 설정해야 하는 걸 알게 되었다.
- 초기에 20000까지 모든 좌표를 세팅하고 이를 사용해서 문제에서 주어진 문제를 해결했다.

**Comment by ramrami-B** [comment]
### 🔗 문제 링크
#74

### 💡 풀이 사항
📆풀이 일자: 2024.01.22
⏰풀이 시간: 37분 18초
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: 구현

### ✍ 풀이 방법
(풀이 접근 및 방법에 대한 설명)

**Comment by jisooolee** [comment]
### 🔗 문제 링크
#39 

### 💡 풀이 사항
📆풀이 일자: 2024.01.21
⏰풀이 시간: 1시간 20분
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: 구현

### ✍ 풀이 방법
- 좌표를 숫자로 변환해주는 calculateNum method와 숫자를 좌표로 변환해주는 calculatePoint method를 선언해주었다.
- 좌표평면을 이차원 배열 형태라고 가정하고, 각 행에서 좌표에 할당된 숫자가 등차수열로 증가한다는 규칙을 이용했다.
- 각 열의 첫 번째 좌표들의 값 역시 등차수열로 증가한다는 규칙을 이용했다.
- calculateNum method를 구현할 때, 등차수열 값을 구하는 공식을 이용했다.
- calculatePoint method를 구현할 때, x 값과 y 값의 합이 동일한 좌표들을 하나의 그룹으로 묶으면, x와 y의 합이 작은 좌표 그룹부터 순차적으로 그룹 안에 포함된 좌표의 개수가 증가한다는 규칙을 이용했다.

**Comment by ensk26** [comment]
https://github.com/Hanbat-Algo-Study/algorithm/pull/89

### 풀이 사항
풀이 일자: 2024.01.23
풀이 시간: 1시 30분
채점 결과: 오답
예상 문제 유형: 구현

### 풀이 방법
- 문제가 이해가 안돼 못 풀었다.
- 10000까지 값을 다 구해, 해당 좌표에 맞는 값을 탐색하는 방법을 이용했다.

**Comment by skdudddl** [comment]
🔗 문제 링크
#72 

💡 풀이 사항
📆풀이 일자: 2024.01.21
⏰풀이 시간: 1시간 +a
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: 구현

✍ 풀이 방법

- 대각선을 포인트로 알려주길래 거기에 대한 규칙을 찾을려고 했다.
- 근데 아무리 생각해도 답이 나오지 않아 힌트를 봤는데 좌표에서 대각선의 합은 일정하다라는 정리를 보고 이를 이용하기로 했다.
- sumToPoint은 맨 끝의 좌표에서의 값은 그 좌표의 x값까지의 합을 이용해서 그 끝점에서 해당 값까지 x,y값을 조정하며 구하는 방식으로 구현했다.
- pointToSum은 해당좌표의 대각선에 해당하는 마지막 값을 구해 그 차이만큼 빼주는 방식으로 구현했다.
