### ISSUE TITLE
[D3] 3499. 퍼펙트 셔플

### ISSUE THREAD

**Issue by GeonHui2** [Hanbat-Algo-Study/algorithm#42]
### 🔗 문제 링크
https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AWGsRbk6AQIDFAVW

### 💡 풀이 사항
📆풀이 일자: 2024.00.00
⏰풀이 시간: 00분 00초
✨채점 결과: 오답🙅‍♀️🙅‍♂️/시간 초과⌛/런타임 에러⏱/정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등

### ✍ 풀이 방법
(풀이 접근 및 방법에 대한 설명)

**Comment by GeonHui2** [comment]
### 🔗 문제 링크
#61 

### 💡 풀이 사항
📆풀이 일자: 2024.01.19
⏰풀이 시간: 15분
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: 구현

### ✍ 풀이 방법
- 홀수일 때와 짝수일 때의 조건을 각각 구현해 주었다.
- 짝수일 때는 N/2개로 나누고 반복문을 통해서 1장씩 결괏값에 추가해 주었다.
- 홀수일 때는 N/2를 해도 1장이 남기 때문에 앞의 덱에 1장을 추가해 주었다.
- 그 후 N/2까지 반복문을 통해서 1장씩 결괏값에 추가하고 앞의 덱에서 마지막 장을 추가해 주었다.

**Comment by ramrami-B** [comment]
### 🔗 문제 링크
#77 

### 💡 풀이 사항
📆풀이 일자: 2024.00.00
⏰풀이 시간: 00분 00초
✨채점 결과: 시간 초과⌛
📃예상 문제 유형: 구현

### ✍ 풀이 방법

**Comment by ramrami-B** [comment]
### 🔗 문제 링크
#78

### 💡 풀이 사항
📆풀이 일자: 2024.01.22
⏰풀이 시간: 18분 03초
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: 구현

### ✍ 풀이 방법
(풀이 접근 및 방법에 대한 설명)

**Comment by ensk26** [comment]
https://github.com/Hanbat-Algo-Study/algorithm/pull/89

### 풀이 사항
풀이 일자: 2024.01.23
풀이 시간: 20분
채점 결과: 정답
예상 문제 유형: 구현

### 풀이 방법
- 카드를 저장을 하고, 절반을 나눠서 조건에 맞는 순서대로 저장을 했다.
- 카드가 홀수인 경우 +1을 해줘 조건에 맞도록 만들었다.

**Comment by skdudddl** [comment]
🔗 문제 링크
#36

💡 풀이 사항
📆풀이 일자: 2024.01.21
⏰풀이 시간: 15분
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: 구현

✍ 풀이 방법

-  N이 짝수일 때와 홀수일 때를 나눠서 조건에 맞게 배열에 넣었다. 
-  홀수일 때는  먼저 놓는 쪽에 남는 한장이전까지는 짝수와 일치하고 그 남은 한장은 배열의 마지막에 넣어주는 방식으로 구현했다.
