### ISSUE TITLE
[D3] 4047. 영준이의 카드 카운팅

### ISSUE THREAD

**Issue by GeonHui2** [Hanbat-Algo-Study/algorithm#43]
### 🔗 문제 링크
https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AWIsY84KEPMDFAWN

### 💡 풀이 사항
📆풀이 일자: 2024.00.00
⏰풀이 시간: 00분 00초
✨채점 결과: 오답🙅‍♀️🙅‍♂️/시간 초과⌛/런타임 에러⏱/정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등

### ✍ 풀이 방법
(풀이 접근 및 방법에 대한 설명)

**Comment by GeonHui2** [comment]
### 🔗 문제 링크
#38 

### 💡 풀이 사항
📆풀이 일자: 2024.01.20
⏰풀이 시간: 20분
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: 구현

### ✍ 풀이 방법
- 크기가 14인 각 무늬 배열을 선언해 주고 각 무늬의 개수를 통해서 문제를 풀었다.
- 값을 하나씩 받으면서 해당 무늬의 i 번째 값이 0이면 [i]++하고 개수를 1개 빼주었고 0이 아니면 ERROR를 출력했다.

**Comment by jisooolee** [comment]
### 🔗 문제 링크
#58 

### 💡 풀이 사항
📆풀이 일자: 2024.01.21
⏰풀이 시간: 41분
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: 구현

### ✍ 풀이 방법
- 반복 횟수를 3으로 나눴을 때의 나머지를 기준으로 각 조건문이 실행되도록 해주었다.
- 값이 카드 종류를 가리키면 kind 변수에 종류 값을 저장해주었다.
- cards 배열을 이용해 각 카드의 종류 별로 등장한 카드를 표시해주었다.
- 반복문을 두 번 돌 때마다 카드 번호를 구하고, cards 배열에 해당 번호의 카드가 이미 존재하면 error를 true로 만들어 ERROR가 출력되도록 해주었으며, 카드가 처음 등장하면 cards 배열에 표시해주고, 해당 종류에서 부족한 카드의 개수를 1 감소해주었다.

**Comment by ensk26** [comment]
https://github.com/Hanbat-Algo-Study/algorithm/pull/73

### 풀이 사항
풀이 일자: 2024.01.21
풀이 시간: 28분
채점 결과: 정답
예상 문제 유형: 구현

### 풀이 방법
- 2차원 배열을 만들어 모양에 따른 값 체크해 개수를 구했다.
- 3개 단위로 끊어주고, 첫번째는 모양을 판단해주고 두번째는 10자리 수이므로 *10을 하고 세번째 수와 더했다.

**Comment by skdudddl** [comment]
🔗 문제 링크
#37 

💡 풀이 사항
📆풀이 일자: 2024.01.20
⏰풀이 시간: 45분
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: 구현

✍ 풀이 방법

- 입력받을 2차원 배열을 만들고 카드 수를 넣을 배열을 13으로 초기화했다.
- 중복 확인을 위한 변수를 만들어 줬다.
- 2차원배열에서 그 카드에 맞는 수에 +1을 해주고 중북확인 변수를 true로 바꿨다.
- 그리고 카드 수를 넣을 배열은 -1 처리를 했다.
- 카드가 중복이라면 error를 아니면 각 카드수를 출력하도록 구현했다.

**Comment by ramrami-B** [comment]
### 🔗 문제 링크
#90 

### 💡 풀이 사항
📆풀이 일자: 2024.00.00
⏰풀이 시간: 1시간 8분
✨채점 결과: 런타임 에러⏱
📃예상 문제 유형: 구현

### ✍ 풀이 방법
4개의 카드 종류, 13개의 카드 개수 크기에 맞게 boolean 2차원 배열을 생성한다.
입력값(문자열)을 받으면서 해당하는 곳에 true로 바꿔준다.
이미 true라면 flag를 true로 바꿔주어 ERROR를 프린트 해주고, 
겹치는 카드가 없다면 마지막에 2차원 배열을 탐색하며 카드 별로 남아있는 카드 수를 파악하고 출력한다,
