### ISSUE TITLE
[D3] 4789. 성공적인 공연 기획

### ISSUE THREAD

**Issue by GeonHui2** [Hanbat-Algo-Study/algorithm#44]
### 🔗 문제 링크
https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AWS2dSgKA8MDFAVT

### 💡 풀이 사항
📆풀이 일자: 2024.00.00
⏰풀이 시간: 00분 00초
✨채점 결과: 오답🙅‍♀️🙅‍♂️/시간 초과⌛/런타임 에러⏱/정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등

### ✍ 풀이 방법
(풀이 접근 및 방법에 대한 설명)

**Comment by GeonHui2** [comment]
### 🔗 문제 링크
#63 

### 💡 풀이 사항
📆풀이 일자: 2024.01.20
⏰풀이 시간: 20분
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: 구현

### ✍ 풀이 방법
- 문제를 이해하는데 시간이 조금 소요되었다.
- i 번째인 때 0이 아니면 지금까지 박수 친 사람이 i - 1이 되어야 한다.
- 하지만 사람이 모자라면 채워지는 사람의 수를 결괏값과 이전의 박수 친 사람의 수에 더해준다.
- 그 후 i 번째의 사람의 수를 더해주면서 문제를 해결했다.

**Comment by jisooolee** [comment]
### 🔗 문제 링크
#63 

### 💡 풀이 사항
📆풀이 일자: 2024.01.21
⏰풀이 시간: 18분
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: 구현

### ✍ 풀이 방법
- 고용한 총 인원 수를 employees에 현재 박수를 치고 있는 총 인원 수를 applause에 저장해주었다.
- index i가 0부터 시작하므로 i번째 순서가 박수를 치려면 필요한 사람 역시 i명이 된다.
- 박수를 치려면 필요한 인원은 1씩 증가하므로 applause가 i보다 작을 때 값이 1 이상 차이날 수 없다.
- 따라서 만약 현재 박수를 치고 있는 인원이 i보다 작다면 applause와 employees를 1 증가해준다.
- 이후 applause에 i번째에 추가로 박수를 치게 될 인원 수를 더해준다.

**Comment by ensk26** [comment]
https://github.com/Hanbat-Algo-Study/algorithm/pull/73

### 풀이 사항
풀이 일자: 2024.01.21
풀이 시간: 10분
채점 결과: 정답
예상 문제 유형: 구현

### 풀이 방법
- 위치가 박수를 치는 필요한 사람이고, 저장된 값이 박수 치는 사람이라서 순회를 하면서 (위치-현재까지 박수 친 사람 합)을 구했다.
- 음수가 나오면 추가적인 박수칠 사람이 필요 없어 0으로 반환했다.

**Comment by skdudddl** [comment]
🔗 문제 링크
#37

💡 풀이 사항
📆풀이 일자: 2024.01.20
⏰풀이 시간: 50+a분
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: 구현

✍ 풀이 방법

-
