### ISSUE TITLE
[D3] 4698. 테네스의 특별한 소수

### ISSUE THREAD

**Issue by GeonHui2** [Hanbat-Algo-Study/algorithm#45]
### 🔗 문제 링크
https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AWRuoqCKkE0DFAXt

### 💡 풀이 사항
📆풀이 일자: 2024.00.00
⏰풀이 시간: 00분 00초
✨채점 결과: 오답🙅‍♀️🙅‍♂️/시간 초과⌛/런타임 에러⏱/정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등

### ✍ 풀이 방법
(풀이 접근 및 방법에 대한 설명)

**Comment by GeonHui2** [comment]
### 🔗 문제 링크
#64 

### 💡 풀이 사항
📆풀이 일자: 2024.01.20
⏰풀이 시간: 20분
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: 구현

### ✍ 풀이 방법
- 시간 복잡도를 생각해서 테스트 케이스를 확인하기 전에 1000000까지 소수인지 확인하는 배열을 구현했다.
- A 이상 B 이하의 범위의 수가 D가 포함하는지 확인하기 위해서 10을 나눴을 때 나머지로 1의 자리부터 확인하고 포함하지 않으면 수를 10으로 나눴을 때 값으로 변경해 주었다.

**Comment by ramrami-B** [comment]
### 🔗 문제 링크
#77 

### 💡 풀이 사항
📆풀이 일자: 2024.00.00
⏰풀이 시간: 00분 00초
✨채점 결과: 시간 초과⌛
📃예상 문제 유형: 구현

### ✍ 풀이 방법

**Comment by jisooolee** [comment]
### 🔗 문제 링크
#75 

### 💡 풀이 사항
📆풀이 일자: 2024.01.22
⏰풀이 시간: 대략 2시간
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: 구현

### ✍ 풀이 방법
- 두 번의 시간 초과를 겪고, 마지막 세 번째 방법을 이용해 정답을 맞힐 수 있었다.
- 첫 번째 시도에서는 반복문 안에서 매번 소수를 생성해주도록 코드를 작성했기 때문에 시간 초과가 났다.
- 두 번째 시도에서는 test_case 반복문 밖에서 범위 내의 모든 소수를 찾고, 소수의 값을 저장한 배열 primes를 이용했다.
- 하지만, 값이 소수인지 아닌지를 판별하려면 추가적으로 primes 배열을 순회해주어야 했기 때문에 여전히 시간 초과 문제가 해결되지 않았다.
- 따라서 마지막 시도에서는 boolean 배열을 선언해주고, index가 소수인 경우 배열의 요소 값을 true로 바꿔주는 방식으로 소수를 표시했다.
- 이 경우 추가로 반복문을 사용할 필요 없이 배열 값으로만 소수 여부를 판단할 수 있기 때문에 시간 초과 문제를 해결할 수 있었다.

**Comment by ensk26** [comment]
https://github.com/Hanbat-Algo-Study/algorithm/pull/73

### 풀이 사항
풀이 일자: 2024.01.21
풀이 시간: 20분
채점 결과: 정답
예상 문제 유형: 구현

### 풀이 방법
- 에라토스테네스 체 방식을 이용해 소수를 미리 1000000까지 구했다.
- 주어진 범위 만큼 특별한 소수인지 판단했다.

**Comment by skdudddl** [comment]
🔗 문제 링크
#56 

💡 풀이 사항
📆풀이 일자: 2024.01.21
⏰풀이 시간: 40분
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: 구현

✍ 풀이 방법

- 시간복잡도를 생각해서 에라토스테네스 체 방식을 이용해서 미리 구했다.
- 10을 나눠주면서 나머지를 이용해 (일의 자리수부터 시작)조건에 맞는  소수를 찾아주는 방식으로 구현했다.
