### ISSUE TITLE
[D3] 5356. 의석이의 세로로 말해요

### ISSUE THREAD

**Issue by GeonHui2** [Hanbat-Algo-Study/algorithm#46]
### 🔗 문제 링크
https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AWVWgkP6sQ0DFAUO

### 💡 풀이 사항
📆풀이 일자: 2024.00.00
⏰풀이 시간: 00분 00초
✨채점 결과: 오답🙅‍♀️🙅‍♂️/시간 초과⌛/런타임 에러⏱/정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등

### ✍ 풀이 방법
(풀이 접근 및 방법에 대한 설명)

**Comment by GeonHui2** [comment]
### 🔗 문제 링크
#64 

### 💡 풀이 사항
📆풀이 일자: 2024.01.20
⏰풀이 시간: 10분
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: 구현

### ✍ 풀이 방법
- 가장 길이가 긴 문자열의 길이를 먼저 확인했다.
- 최대 길이만큼 반복문을 구현하고 현재 길이의 배열이 넘어서지 않으면 결괏값에 추가하는 방법으로 문제를 해결했다.

**Comment by ensk26** [comment]
https://github.com/Hanbat-Algo-Study/algorithm/pull/73

### 풀이 사항
풀이 일자: 2024.01.21
풀이 시간: 10분
채점 결과: 정답
예상 문제 유형: 구현

### 풀이 방법
- 배열에 저장 후, 열 기준으로 탐색하면서 값을 저장했다.

**Comment by skdudddl** [comment]
🔗 문제 링크
#56 

💡 풀이 사항
📆풀이 일자: 2024.01.21
⏰풀이 시간: 40분
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: 구현

✍ 풀이 방법

- max_column를 구해서 반복문을 돌렸다. .
- 각 row의 길이만큼 row를 StringBuilder에 append해주는 방식으로 구현했다.
