### ISSUE TITLE
[D3] 6485. 삼성시의 버스 노선

### ISSUE THREAD

**Issue by GeonHui2** [Hanbat-Algo-Study/algorithm#47]
### 🔗 문제 링크
https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AWczm7QaACgDFAWn

### 💡 풀이 사항
📆풀이 일자: 2024.00.00
⏰풀이 시간: 00분 00초
✨채점 결과: 오답🙅‍♀️🙅‍♂️/시간 초과⌛/런타임 에러⏱/정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등

### ✍ 풀이 방법
(풀이 접근 및 방법에 대한 설명)

**Comment by GeonHui2** [comment]
### 🔗 문제 링크
#64 

### 💡 풀이 사항
📆풀이 일자: 2024.01.20
⏰풀이 시간: 10분
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: 구현

### ✍ 풀이 방법
- 해당 번호의 버스가 노선의 조건을 충족하면 결괏값++ 해주었다.

**Comment by ramrami-B** [comment]
### 🔗 문제 링크
#87 

### 💡 풀이 사항
📆풀이 일자: 2024.01.22
⏰풀이 시간: 23분 52초
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: 구현

### ✍ 풀이 방법
~_졸려서 문제 이해하는데 오래 걸렸다,,,_~

**Comment by jisooolee** [comment]
### 🔗 문제 링크
#79

### 💡 풀이 사항
📆풀이 일자: 2024.01.22
⏰풀이 시간: 5분
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: 구현

### ✍ 풀이 방법
- 각 노선을 순회하면서 i번째 정거장을 지나면 해당되는 정거장의 결과 값을 1 증가해주었다.

**Comment by ensk26** [comment]
https://github.com/Hanbat-Algo-Study/algorithm/pull/89

### 풀이 사항
풀이 일자: 2024.01.23
풀이 시간: 20분
채점 결과: 정답
예상 문제 유형: 구현

### 풀이 방법
-  각 노선이 겹치는 개수 배열 만들어 정거장마다 몇 대가 오는지 저장을 했다.
- 문제에서 요구하는 정거장을 해당 배열값으로 반환해 주었다.

**Comment by skdudddl** [comment]
🔗 문제 링크
#56

💡 풀이 사항
📆풀이 일자: 2024.01.21
⏰풀이 시간: 30분
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: 구현

✍ 풀이 방법

-A,B의 각각 의 배열을 만들어준다.
- A,B 사이에 있는 값을 sum이라는 배열을 만들어 +1씩 처리했다.
- 그리고 c에 해당하는 sum의 값을 출력하도록 구현했다.
