### ISSUE TITLE
[D3] 7964. 부먹왕국의 차원 관문

### ISSUE THREAD

**Issue by GeonHui2** [Hanbat-Algo-Study/algorithm#48]
### 🔗 문제 링크
https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AWuSgKpqmooDFASy

### 💡 풀이 사항
📆풀이 일자: 2024.00.00
⏰풀이 시간: 00분 00초
✨채점 결과: 오답🙅‍♀️🙅‍♂️/시간 초과⌛/런타임 에러⏱/정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등

### ✍ 풀이 방법
(풀이 접근 및 방법에 대한 설명)

**Comment by GeonHui2** [comment]
### 🔗 문제 링크
#67 

### 💡 풀이 사항
📆풀이 일자: 2024.01.20
⏰풀이 시간: 15분
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: 구현

### ✍ 풀이 방법
- 0이 나오게 되면 cnt++ 해주었고 0이 아니면 D로 나누어서 결괏값에 더하면서 cnt를 0으로 초기화했다.

**Comment by ramrami-B** [comment]
### 🔗 문제 링크
#88 
### 💡 풀이 사항
📆풀이 일자: 2024.00.00
⏰풀이 시간: 16분 24초
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: 구현

### ✍ 풀이 방법
도시의 차원관문이 파괴 되었는지 남았는지를 0과 1로 표현한 배열에서 연속된 0의 개수가 제한 거리만큼 되면 차원관문을 세워주면(answer++) 된다.
"연속된" 0의 개수를 세어야 하므로 1이 나오면 cnt를 초기화 해줘야 한다.

**Comment by jisooolee** [comment]
### 🔗 문제 링크
#80

### 💡 풀이 사항
📆풀이 일자: 2024.01.22
⏰풀이 시간: 14분
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: 구현

### ✍ 풀이 방법
- 가장 첫 번째로 등장하는 1을 찾아 idx에 저장해주었다.
- 만약 1이 없다면 N/D 값을 결과로 출력하고 다음 반복을 실행하도록 하였다.
- 반복문을 두 번 실행하여, 한 번은 idx에서부터 역순으로 관문을 검사하도록 해주었으며, 다른 한 번은 idx에서부터 순차적으로 관문을 검사하도록 해주었다.
- 1에서부터 다음 관문까지 갈 수 있는 남은 거리를 left에 저장해주었다.
- 만약 해당 관문의 값이 0이고, left 값이 0이라면 세워야하는 관문의 개수를 1 증가해주고 left 값을 거리 값에 알맞게 초기화해주었다.
- 관문의 값이 0이고 left 값이 0이 아니라면 left 값을 1 감소해주었다.
- 관문의 값이 1이면 left 값을 거리 값에 맞게 초기화해주었다.
-

**Comment by ensk26** [comment]
https://github.com/Hanbat-Algo-Study/algorithm/pull/73

### 풀이 사항
풀이 일자: 2024.01.21
풀이 시간: 35분
채점 결과: 정답
예상 문제 유형: 구현

### 풀이 방법
- 차원의 문을 상태를 저장한 배열을 순회하면서, 거리 내에 있는 차원의 문 위치를 저장하고
- 가장 최근의 차원의 문 위치에서+d한 것과 현재 위치가 동일하면서, 현재 위치에 차원의 문이 없으면 하나 만들어줬다.

**Comment by skdudddl** [comment]
🔗 문제 링크
#56

💡 풀이 사항
📆풀이 일자: 2024.01.21
⏰풀이 시간: 30분
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: 구현

✍ 풀이 방법

-  도시수만큼 배열을 만들어주었다.
- 그만큼 반복문을 돌면서 배열값이 0일 때 cnt를 +1해줬고 거리와 같을 때 cnt를 0으로 초기화 했다.
- 배열값이 1일 때는 cnt를 0으로 초기화하여 그 장소에서 다시 cnt를 세주는 방식으로 구현했다.
