### ISSUE TITLE
[D3] 7087. 문제 제목 붙이기

### ISSUE THREAD

**Issue by GeonHui2** [Hanbat-Algo-Study/algorithm#49]
### 🔗 문제 링크
https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AWkIdD46A5EDFAXC

### 💡 풀이 사항
📆풀이 일자: 2024.00.00
⏰풀이 시간: 00분 00초
✨채점 결과: 오답🙅‍♀️🙅‍♂️/시간 초과⌛/런타임 에러⏱/정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등

### ✍ 풀이 방법
(풀이 접근 및 방법에 대한 설명)

**Comment by GeonHui2** [comment]
### 🔗 문제 링크
#68  

### 💡 풀이 사항
📆풀이 일자: 2024.01.20
⏰풀이 시간: 15분
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: 구현

### ✍ 풀이 방법
- 확인해야 하는 알파벳을 A로 시작하여서 해당 문제가 해당 알파벳으로 시작하는지 확인했고 시작한다면 알파벳에 1을 더해주었다.

**Comment by ramrami-B** [comment]
### 🔗 문제 링크
#81

### 💡 풀이 사항
📆풀이 일자: 2024.01.20
⏰풀이 시간: 13분 5초
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: 구현

### ✍ 풀이 방법

**Comment by jisooolee** [comment]
### 🔗 문제 링크
#83

### 💡 풀이 사항
📆풀이 일자: 2024.01.22
⏰풀이 시간: 1시간 24분
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: 구현

### ✍ 풀이 방법
- 문제의 조건을 잘못 이해해서 시간을 많이 낭비했다.
- 등장한 알파벳을 모두 배열에 저장해주고, 배열을 순회하면서 연속적으로 나온 알파벳의 개수를 세어주었다.

**Comment by ensk26** [comment]
https://github.com/Hanbat-Algo-Study/algorithm/pull/73

### 풀이 사항
풀이 일자: 2024.01.21
풀이 시간: 11분
채점 결과: 정답
예상 문제 유형: 구현

### 풀이 방법
- 제목 앞 글자만 -'A'를 빼 해당값 배열에 true를 저장을 해서, 배열을 순회하면서 false가 나오기전까지의 개수를 구했다.

**Comment by skdudddl** [comment]
🔗 문제 링크
#56

💡 풀이 사항
📆풀이 일자: 2024.01.20
⏰풀이 시간: 15분
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: 구현

✍ 풀이 방법

- 대문자를 비교하기 전에 각 문장의 앞글자만 가져와서 배열을 만들었다.
- 그리고 sort()를 이용해서 정렬하였다.
- 처음에는 빡빡하게 각 하나씩 보면서 A,B,C,,,순서로 나오게 중복제거 처리를 시도하였으나 너무 힘들어서 포기했다.
- 그래서 너프하게 각 대문자의 순서가 맞을 때의 조건을 걸어 그때 cnt와 아스키코드값을 더해주는 방식으로 구현했다.
