### ISSUE TITLE
[D2] 1961. 숫자 배열 회전

### ISSUE THREAD

**Issue by GeonHui2** [Hanbat-Algo-Study/algorithm#5]
### 문제 링크
https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AV5Pq-OKAVYDFAUq

### 풀이 사항
풀이 일자: 2024.00.00
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등

### 풀이 방법
(풀이 접근 및 방법에 대한 설명)

**Comment by GeonHui2** [comment]
### 문제 링크
#9 

### 풀이 사항
풀이 일자: 2024.01.13
풀이 시간: 20분
채점 결과: 정답
예상 문제 유형: 구현

### 풀이 방법
- 처음에는 회전하는 함수를 구현해서 하려고 했었다.
- 하지만 생각보다 구현하는데 복잡해서 제한된 시간 내에서 90도, 180도, 270도 회전한 모양을 각각 구현해도 될 거 같았다.
- 그래서 반복문을 통해서 구현 후 결괏값을 저장하는 배열에 저장했다.

**Comment by jisooolee** [comment]
### 문제 링크
#10 

### 풀이 사항
풀이 일자: 2024.01.13
풀이 시간: 38분
채점 결과: 정답
예상 문제 유형: 구현

### 풀이 방법
- 원래 배열의 각 요소들의 index가 90도, 180도, 270도 회전한 배열에서 어떻게 바뀌는지 규칙을 찾았다.
- 반복문을 돌면서 90도, 180도, 270도 회전한 배열의 올바른 index에 각각의 요소들을 넣어주었다.

**Comment by ensk26** [comment]
문제 링크
https://github.com/Hanbat-Algo-Study/algorithm/pull/15

풀이 사항
풀이 일자: 2024.01.15
풀이 시간: 30분
채점 결과: 정답
예상 문제 유형: 구현

풀이 방법
- 시계 방향으로 90도 회전하는 메서드를 생성해서 90도 배열 -> 180 도 배열 -> 270도 배열 순으로 이전 결과값에 한번씩만 적용을 했다.

**Comment by ramrami-B** [comment]
### 🔗 #24 

### 💪🏻 풀이 사항
📅 풀이 일자: 2024.01.17
⏰ 풀이 시간: 31분 23초
🥺 채점 결과: 정답✅
💡 예상 문제 유형: 구현

### ✍🏻풀이 방법
먼저 원본 배열을 만들어 준 다음, 90도, 180도, 270도 회전 했을 때의 모양을 담은 배열을 만들어 준다.
말로 하면 조금 어려운데 그림을 그려보면 원본 (0,0) 위치에 90도 회전한 배열은 원본 배열의 (2,0)값을 가지고 있는 것을 알 수 있다. 그 둘 사이의 규칙을 찾아서 지정해 주면 간단하게 풀리는 문제!

쉽게 풀리는 대신 반복되는 코드가 많아서 최대한 함수로 묶어보려고 했다
