### ISSUE TITLE
[D3] 7272. 안경이 없어!

### ISSUE THREAD

**Issue by GeonHui2** [Hanbat-Algo-Study/algorithm#50]
### 🔗 문제 링크
https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AWl0ZQ8qn7UDFAXz

### 💡 풀이 사항
📆풀이 일자: 2024.00.00
⏰풀이 시간: 00분 00초
✨채점 결과: 오답🙅‍♀️🙅‍♂️/시간 초과⌛/런타임 에러⏱/정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등

### ✍ 풀이 방법
(풀이 접근 및 방법에 대한 설명)

**Comment by GeonHui2** [comment]
### 🔗 문제 링크
#69 

### 💡 풀이 사항
📆풀이 일자: 2024.01.20
⏰풀이 시간: 15분
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: 구현

### ✍ 풀이 방법
- 먼저 처음 단어와 두 번째 단어의 길이가 다르면 DIFF가 나오게 하였다.
- 길이가 같다면 해당 번째의 단어의 구멍 개수를 비교해서 다르면 DIFF가 나오게 하였다.

**Comment by ramrami-B** [comment]
### 🔗 문제 링크
#82

### 💡 풀이 사항
📆풀이 일자: 2024.00.00
⏰풀이 시간: 00분 00초
✨채점 결과: 오답🙅‍♀️🙅‍♂️/시간 초과⌛/런타임 에러⏱/정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등

### ✍ 풀이 방법
(풀이 접근 및 방법에 대한 설명)

**Comment by jisooolee** [comment]
### 🔗 문제 링크
#84

### 💡 풀이 사항
📆풀이 일자: 2024.01.22
⏰풀이 시간: 14분
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: 구현

### ✍ 풀이 방법
- 각 알파벳의 구멍의 개수를 알파벳 배열에 저장한 후 이용해주었다.
- 두 문자열의 길이가 다르면 DIFF를 출력하고 다음 case를 검사하도록 하였다.

**Comment by ensk26** [comment]
https://github.com/Hanbat-Algo-Study/algorithm/pull/73

### 풀이 사항
풀이 일자: 2024.01.21
풀이 시간: 50분
채점 결과: 정답
예상 문제 유형: 구현

### 풀이 방법
- 구명이 하나인 알파벳 배열을 저장한 후 사용했다
- indexOf를 이용해 해당 알파벳이 있는지 확인했다.
- 길이가 다른경우는 DIFF를 출력했다.
- equals로 char랑 String 비교는 안된다.

**Comment by skdudddl** [comment]
🔗 문제 링크
#57

💡 풀이 사항
📆풀이 일자: 2024.01.21
⏰풀이 시간: 40분
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: 구현

✍ 풀이 방법

- StringTokenizer를 이용해서 s1,s2를 구했다.
- 먼저 길이차이로 맞는지 다른지 확인한 후 totalCircle함수로 0의갯수를 확인했다.
- totalCircle 함수는 각 s1,s2의 각 요소의 circle의 갯수를 비교하는 방식으로 구현했다.
