### ISSUE TITLE
[D3] 7236. 저수지의 물의 총 깊이 구하기

### ISSUE THREAD

**Issue by GeonHui2** [Hanbat-Algo-Study/algorithm#51]
### 🔗 문제 링크
https://swexpertacademy.com/main/code/userProblem/userProblemDetail.do?contestProbId=AWlTKTUqCN8DFAVS

### 💡 풀이 사항
📆풀이 일자: 2024.00.00
⏰풀이 시간: 00분 00초
✨채점 결과: 오답🙅‍♀️🙅‍♂️/시간 초과⌛/런타임 에러⏱/정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등

### ✍ 풀이 방법
(풀이 접근 및 방법에 대한 설명)

**Comment by GeonHui2** [comment]
### 🔗 문제 링크
#70 

### 💡 풀이 사항
📆풀이 일자: 2024.01.21
⏰풀이 시간: 10분
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: 구현

### ✍ 풀이 방법
- 모든 결괏값의 최솟값을 고민했을 때 1이라는 점을 이용해서 문제를 구현했다.
- 모든 구간을 탐색하고 해당 구역이 W라면 주변의 구역을 확인해서 W의 개수를 카운트했다.
- 카운트 값과 결괏값을 비교해서 큰 값을 결괏값에 저장했다.

**Comment by jisooolee** [comment]
### 🔗 문제 링크
#86 

### 💡 풀이 사항
📆풀이 일자: 2024.01.22
⏰풀이 시간: 15분
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: 구현

### ✍ 풀이 방법
- 수업 시간에 배운 팔방탐색을 이용해 구현했다.

**Comment by ramrami-B** [comment]
### 🔗 문제 링크
#90 

### 💡 풀이 사항
📆풀이 일자: 2024.01.23
⏰풀이 시간: 16분 58초
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: 구현 (완전 탐색)

### ✍ 풀이 방법
모든 물이 있는 곳에서 주위를 탐색하여 주위에 물이 몇 개 있는 지 센다.
세면서 max값 업데이트 해주고 max값을 정답으로 제출

**Comment by skdudddl** [comment]
🔗 문제 링크
#57

💡 풀이 사항
📆풀이 일자: 2024.01.21
⏰풀이 시간: 40분
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: 구현

✍ 풀이 방법

- max_water를 최소값은 1임을 생각하여 1로 초기화하였다.
- 8방순회를 이용하여 그 주변 water가 있을 때 더해주는 방식으로 구현했다.
