### ISSUE TITLE
[실버4] 1244. 스위치 켜고 끄기

### ISSUE THREAD

**Issue by ramrami-B** [Hanbat-Algo-Study/algorithm#92]
### 🔗 문제 링크
https://www.acmicpc.net/problem/1244

### 💡 풀이 사항
📆풀이 일자: 2024.00.00
⏰풀이 시간: 00분 00초
✨채점 결과: 오답🙅‍♀️🙅‍♂️/시간 초과⌛/런타임 에러⏱/정답🙆‍♀️🙆‍♂️
📃예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등

### ✍ 풀이 방법
(풀이 접근 및 방법에 대한 설명)

**Comment by ramrami-S** [comment]
### 🔗 문제 링크
#97 

### 💡 풀이 사항
📆풀이 일자: 2024.01.25
⏰풀이 시간: 38분 51초
✨채점 결과: 오답🙅‍♀️ (도와죠...)
📃예상 문제 유형: 구현

### ✍ 풀이 방법
processBoy 함수: 학생이 남자일 경우 자신의 숫자의 배수에서 상태 변경(changeStatus 함수)
processGirl 함수: 학생이 여자일 경우 자신의 숫자와 1~가능한 수까지 빼고 더한 인덱스에서 상태 변경

**Comment by skdudddl** [comment]
🔗 문제 링크
#85 

💡 풀이 사항
📆풀이 일자: 2024.01.23
⏰풀이 시간: 40분
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: 구현

✍ 풀이 방법

- 성별에 따라 man, woman의 함수를 실행하도록 구현했다.
- 남자인 경우 배수에서 상태 변경, 여자일 경우는 자기와 자기옆자리 자리 바꿔주는 방법으로 구현했다.
- 그리고 출력할 때 20배수일 때는 한줄 띄도록 반복문을 실행했다.

**Comment by GeonHui2** [comment]
### 🔗 문제 링크
#93 

### 💡 풀이 사항
📆풀이 일자: 2024.01.22
⏰풀이 시간: 35분
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: 구현

### ✍ 풀이 방법
- 남자의 경우 입력받은 수의 배수들의 상태를 반대로 만들어준다.
- 여자의 경우 해당하는 위치에서 좌우로 같은 상태일 때까지 범위를 지정해 주고 상태를 바꿔준다.

**Comment by jisooolee** [comment]
### 🔗 문제 링크
#124 

### 💡 풀이 사항
📆풀이 일자: 2024.01.25
⏰풀이 시간: 2시간
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: 구현

### ✍ 풀이 방법
- 남자일 경우 배열 전체를 순회하며 index가 입력 받은 숫자의 배수일 때 switch 값을 변경해주었다.
- 여자일 경우 입력 받은 숫자를 기준으로 index를 양 방향으로 옮겨가면서 대칭이 깨지기 직전까지 switch 값을 변경해주었다.

**Comment by ensk26** [comment]
### 🔗 문제 링크
https://github.com/Hanbat-Algo-Study/algorithm/pull/128

### 💡 풀이 사항
📆풀이 일자: 2024.01.13
⏰풀이 시간: 30분
✨채점 결과: 정답🙆‍♀️
📃예상 문제 유형: 구현

### ✍ 풀이 방법
남학생인 경우 자기가 받은 수 배수로 반복문을 돌면서 상태를 바꿔주었다.
여학생인 경우 인접한 두 수 값이 같으면 상태를 변경해주었다.
